// protoc-gen-cqrs generates CQRS infrastructure from proto files.
//
// This plugin generates files with the .cqrs.pb.go extension to clearly indicate
// they are generated by the CQRS plugin (for transport and routing).
//
// Generated files:
//   - *_client.cqrs.pb.go - Low-level client implementations over transport
//   - *_sdk.cqrs.pb.go - Type-safe SDK clients for commands and queries
//   - *_server.cqrs.pb.go - Server-side routing and request handling
//
// Generation modes (use --cqrs_opt=generate=MODE):
//   - all (default) - Generate all files
//   - client - Only generate *_client.cqrs.pb.go and *_sdk.cqrs.pb.go
//   - server - Only generate *_server.cqrs.pb.go
//
// Example usage:
//
//	# Generate all files (default)
//	protoc --go_out=. --cqrs_out=. proto/**/*.proto
//
//	# Generate only client files
//	protoc --go_out=. --cqrs_out=. --cqrs_opt=generate=client proto/**/*.proto
//
// Configuration via Proto Options:
//
// The plugin uses custom proto options (defined in cqrs/options.proto):
//
//	Service level (required):
//	 - option (cqrs.service) = {
//	     service_type: SERVICE_TYPE_COMMAND
//	   }
package main

import (
	"flag"
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/plaenen/eventstore/pkg/cqrs"
	"github.com/plaenen/eventstore/pkg/eventsourcing"
)

var version = "0.0.1"

// Generation mode controls what files to generate
type GenerationMode string

const (
	GenerateModeAll    GenerationMode = "all"    // Generate all files (default)
	GenerateModeClient GenerationMode = "client" // Only generate client files
	GenerateModeServer GenerationMode = "server" // Only generate server files
)

var generateMode GenerationMode = GenerateModeAll

func main() {
	var flags flag.FlagSet
	flags.Var((*genModeFlag)(&generateMode), "generate",
		"Controls what files to generate: all (default), client, or server")

	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			generateFile(gen, f)
		}

		return nil
	})
}

// genModeFlag implements flag.Value for GenerationMode
type genModeFlag GenerationMode

func (g *genModeFlag) String() string {
	return string(*g)
}

func (g *genModeFlag) Set(s string) error {
	switch s {
	case "all", "client", "server":
		*g = genModeFlag(s)
		return nil
	default:
		return fmt.Errorf("invalid generate mode: %s (must be: all, client, or server)", s)
	}
}

func (g *genModeFlag) Get() interface{} {
	return GenerationMode(*g)
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	// Find services with CQRS options
	services := findServices(file)
	if len(services) == 0 {
		return
	}

	// Extract aggregate names from services
	aggregateNames := make(map[string]bool)
	for _, svc := range services {
		if svc.AggregateName != "" {
			aggregateNames[svc.AggregateName] = true
		}
	}

	// Generate client/SDK files if mode allows
	if generateMode == GenerateModeAll || generateMode == GenerateModeClient {
		if len(aggregateNames) > 0 && hasServiceMethods(services) {
			generateCQRSClient(gen, file, aggregateNames, services)
			generateCQRSSDK(gen, file, aggregateNames, services)
		}
	}

	// Generate server file if mode allows
	if generateMode == GenerateModeAll || generateMode == GenerateModeServer {
		if hasServiceMethods(services) {
			generateCQRSServer(gen, file, services)
		}
	}
}

// ServiceInfo holds information about CQRS services
type ServiceInfo struct {
	Name          string
	Commands      []*protogen.Method
	Queries       []*protogen.Method
	Service       *protogen.Service
	AggregateName string
}

// Helper functions

func getCQRSServiceOptions(svc *protogen.Service) *cqrs.ServiceOptions {
	if proto.HasExtension(svc.Desc.Options(), cqrs.E_Service) {
		return proto.GetExtension(
			svc.Desc.Options(),
			cqrs.E_Service,
		).(*cqrs.ServiceOptions)
	}
	return nil
}

func getEventSourcingServiceOptions(svc *protogen.Service) *eventsourcing.ServiceOptions {
	if proto.HasExtension(svc.Desc.Options(), eventsourcing.E_Service) {
		return proto.GetExtension(
			svc.Desc.Options(),
			eventsourcing.E_Service,
		).(*eventsourcing.ServiceOptions)
	}
	return nil
}

func hasServiceMethods(services []*ServiceInfo) bool {
	for _, svc := range services {
		if len(svc.Commands) > 0 || len(svc.Queries) > 0 {
			return true
		}
	}
	return false
}

func findServices(file *protogen.File) []*ServiceInfo {
	var services []*ServiceInfo

	for _, svc := range file.Services {
		name := string(svc.Desc.Name())

		// Get CQRS options
		cqrsOpts := getCQRSServiceOptions(svc)
		if cqrsOpts == nil {
			// No CQRS options - skip
			continue
		}

		// Get aggregate name from eventsourcing options (if present)
		var aggregateName string
		esOpts := getEventSourcingServiceOptions(svc)
		if esOpts != nil {
			aggregateName = esOpts.GetAggregateName()
		}

		// Determine service type
		var serviceType string
		switch cqrsOpts.ServiceType {
		case cqrs.ServiceType_SERVICE_TYPE_COMMAND:
			serviceType = "command"
		case cqrs.ServiceType_SERVICE_TYPE_QUERY:
			serviceType = "query"
		case cqrs.ServiceType_SERVICE_TYPE_UNSPECIFIED:
			// Fall back to naming convention
			if strings.HasSuffix(name, "CommandService") {
				serviceType = "command"
			} else if strings.HasSuffix(name, "QueryService") {
				serviceType = "query"
			} else {
				// No type specified - skip
				continue
			}
		default:
			// Unknown type - skip
			continue
		}

		info := &ServiceInfo{
			Name:          name,
			Service:       svc,
			AggregateName: aggregateName,
			Commands:      make([]*protogen.Method, 0),
			Queries:       make([]*protogen.Method, 0),
		}

		// Categorize methods
		for _, method := range svc.Methods {
			if serviceType == "command" {
				info.Commands = append(info.Commands, method)
			} else if serviceType == "query" {
				info.Queries = append(info.Queries, method)
			}
		}

		services = append(services, info)
	}

	return services
}

func generateCQRSClient(gen *protogen.Plugin, file *protogen.File, aggregateNames map[string]bool, services []*ServiceInfo) {
	clientFilename := file.GeneratedFilenamePrefix + "_client.cqrs.pb.go"
	g := gen.NewGeneratedFile(clientFilename, file.GoImportPath)

	// Header
	g.P("// Code generated by protoc-gen-cqrs. DO NOT EDIT.")
	g.P("// version: ", version)
	g.P("// Client SDK for ", file.Desc.Name())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P()
	g.P(`	"github.com/plaenen/eventstore/pkg/eventsourcing"`)
	g.P(")")
	g.P()

	// Generate aggregate-specific client for each aggregate
	for aggName := range aggregateNames {
		clientName := aggName + "Client"

		g.P("// ", clientName, " provides type-safe methods for ", aggName, " commands and queries")
		g.P("type ", clientName, " struct {")
		g.P("	transport eventsourcing.Transport")
		g.P("}")
		g.P()

		g.P("// New", clientName, " creates a new type-safe client for ", aggName)
		g.P("func New", clientName, "(transport eventsourcing.Transport) *", clientName, " {")
		g.P("	return &", clientName, "{transport: transport}")
		g.P("}")
		g.P()

		// Find services for this aggregate
		for _, svc := range services {
			if svc.AggregateName != aggName {
				continue
			}

			// Generate command methods
			for _, method := range svc.Commands {
				methodName := method.GoName
				inputType := g.QualifiedGoIdent(method.Input.GoIdent)
				outputType := g.QualifiedGoIdent(method.Output.GoIdent)
				subject := string(file.Desc.Package()) + "." + svc.Name + "." + methodName

				g.P("// ", methodName, " sends a ", methodName, " command and returns the response")
				g.P("func (c *", clientName, ") ", methodName, "(ctx context.Context, cmd *", inputType, ") (*", outputType, ", *eventsourcing.AppError) {")
				g.P("	// Send request via transport")
				g.P(`	resp, err := c.transport.Request(ctx, "`, subject, `", cmd)`)
				g.P("	if err != nil {")
				g.P("		return nil, &eventsourcing.AppError{")
				g.P(`			Code:    "TRANSPORT_ERROR",`)
				g.P("			Message: err.Error(),")
				g.P("		}")
				g.P("	}")
				g.P()
				g.P("	// Check if request succeeded")
				g.P("	if !resp.Success {")
				g.P("		return nil, resp.GetError()")
				g.P("	}")
				g.P()
				g.P("	// Unpack response data")
				g.P("	result := &", outputType, "{}")
				g.P("	if err := resp.UnpackData(result); err != nil {")
				g.P("		return nil, &eventsourcing.AppError{")
				g.P(`			Code:    "INVALID_RESPONSE",`)
				g.P("			Message: err.Error(),")
				g.P("		}")
				g.P("	}")
				g.P()
				g.P("	return result, nil")
				g.P("}")
				g.P()
			}

			// Generate query methods
			for _, method := range svc.Queries {
				methodName := method.GoName
				inputType := g.QualifiedGoIdent(method.Input.GoIdent)
				outputType := g.QualifiedGoIdent(method.Output.GoIdent)
				subject := string(file.Desc.Package()) + "." + svc.Name + "." + methodName

				g.P("// ", methodName, " executes a ", methodName, " query and returns the result")
				g.P("func (c *", clientName, ") ", methodName, "(ctx context.Context, query *", inputType, ") (*", outputType, ", *eventsourcing.AppError) {")
				g.P("	// Send request via transport")
				g.P(`	resp, err := c.transport.Request(ctx, "`, subject, `", query)`)
				g.P("	if err != nil {")
				g.P("		return nil, &eventsourcing.AppError{")
				g.P(`			Code:    "TRANSPORT_ERROR",`)
				g.P("			Message: err.Error(),")
				g.P("		}")
				g.P("	}")
				g.P()
				g.P("	// Check if request succeeded")
				g.P("	if !resp.Success {")
				g.P("		return nil, resp.GetError()")
				g.P("	}")
				g.P()
				g.P("	// Unpack response data")
				g.P("	result := &", outputType, "{}")
				g.P("	if err := resp.UnpackData(result); err != nil {")
				g.P("		return nil, &eventsourcing.AppError{")
				g.P(`			Code:    "INVALID_RESPONSE",`)
				g.P("			Message: err.Error(),")
				g.P("		}")
				g.P("	}")
				g.P()
				g.P("	return result, nil")
				g.P("}")
				g.P()
			}
		}
	}
}

func generateCQRSServer(gen *protogen.Plugin, file *protogen.File, services []*ServiceInfo) {
	serverFilename := file.GeneratedFilenamePrefix + "_server.cqrs.pb.go"
	g := gen.NewGeneratedFile(serverFilename, file.GoImportPath)

	// Header
	g.P("// Code generated by protoc-gen-cqrs. DO NOT EDIT.")
	g.P("// version: ", version)
	g.P("// Server service for ", file.Desc.Name())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"fmt"`)
	g.P()
	g.P(`	"github.com/plaenen/eventstore/pkg/eventsourcing"`)
	g.P(`	"google.golang.org/protobuf/proto"`)
	g.P(")")
	g.P()

	// Generate server for each service
	for _, svc := range services {
		esOpts := getEventSourcingServiceOptions(svc.Service)
		useAggregateHandler := esOpts != nil && esOpts.GetAggregateHandler()

		serverName := svc.Name + "Server"
		var handlerName string

		if useAggregateHandler {
			handlerName = esOpts.GetAggregateName() + "Handler"
		} else {
			handlerName = svc.Name + "Handler"
		}

		// Server struct
		g.P("// ", serverName, " routes requests to the ", handlerName, " implementation")
		g.P("type ", serverName, " struct {")
		g.P("	server  eventsourcing.Server")
		g.P("	handler ", handlerName)
		g.P("}")
		g.P()

		// Constructor
		g.P("// New", serverName, " creates a new server")
		g.P("func New", serverName, "(server eventsourcing.Server, handler ", handlerName, ") *", serverName, " {")
		g.P("	return &", serverName, "{")
		g.P("		server:  server,")
		g.P("		handler: handler,")
		g.P("	}")
		g.P("}")
		g.P()

		// Start method
		g.P("// Start registers handlers and starts the server")
		g.P("func (s *", serverName, ") Start(ctx context.Context) error {")

		// Register handlers for commands
		for _, method := range svc.Commands {
			methodName := method.GoName
			subject := string(file.Desc.Package()) + "." + svc.Name + "." + methodName

			g.P(`	if err := s.server.RegisterHandler("`, subject, `", s.handle`, methodName, `); err != nil {`)
			g.P("		return fmt.Errorf(\"failed to register ", methodName, ": %w\", err)")
			g.P("	}")
		}

		// Register handlers for queries
		for _, method := range svc.Queries {
			methodName := method.GoName
			subject := string(file.Desc.Package()) + "." + svc.Name + "." + methodName

			g.P(`	if err := s.server.RegisterHandler("`, subject, `", s.handle`, methodName, `); err != nil {`)
			g.P("		return fmt.Errorf(\"failed to register ", methodName, ": %w\", err)")
			g.P("	}")
		}

		g.P()
		g.P("	return s.server.Start(ctx)")
		g.P("}")
		g.P()

		// Generate handler wrapper methods for commands
		for _, method := range svc.Commands {
			methodName := method.GoName
			inputType := g.QualifiedGoIdent(method.Input.GoIdent)

			g.P("func (s *", serverName, ") handle", methodName, "(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {")
			g.P("	req := request.(*", inputType, ")")

			if useAggregateHandler {
				g.P("	// Extract method options from context (set by middleware)")
				g.P("	opts := eventsourcing.ExtractMethodOptionsFromContext(ctx)")
				g.P("	result, err := s.handler.", methodName, "(ctx, req, opts...)")
				g.P("	if err != nil {")
				g.P("		return &eventsourcing.Response{")
				g.P("			Success: false,")
				g.P("			Error:   eventsourcing.ErrorToAppError(err),")
				g.P("		}, nil")
				g.P("	}")
			} else {
				g.P("	result, appErr := s.handler.", methodName, "(ctx, req)")
				g.P("	if appErr != nil {")
				g.P("		return &eventsourcing.Response{")
				g.P("			Success: false,")
				g.P("			Error:   appErr,")
				g.P("		}, nil")
				g.P("	}")
			}

			g.P("	return eventsourcing.NewSuccessResponse(result)")
			g.P("}")
			g.P()
		}

		// Generate handler wrapper methods for queries
		for _, method := range svc.Queries {
			methodName := method.GoName
			inputType := g.QualifiedGoIdent(method.Input.GoIdent)

			g.P("func (s *", serverName, ") handle", methodName, "(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {")
			g.P("	req := request.(*", inputType, ")")

			if useAggregateHandler {
				g.P("	// Extract method options from context (set by middleware)")
				g.P("	opts := eventsourcing.ExtractMethodOptionsFromContext(ctx)")
				g.P("	result, err := s.handler.", methodName, "(ctx, req, opts...)")
				g.P("	if err != nil {")
				g.P("		return &eventsourcing.Response{")
				g.P("			Success: false,")
				g.P("			Error:   eventsourcing.ErrorToAppError(err),")
				g.P("		}, nil")
				g.P("	}")
			} else {
				g.P("	result, appErr := s.handler.", methodName, "(ctx, req)")
				g.P("	if appErr != nil {")
				g.P("		return &eventsourcing.Response{")
				g.P("			Success: false,")
				g.P("			Error:   appErr,")
				g.P("		}, nil")
				g.P("	}")
			}

			g.P("	return eventsourcing.NewSuccessResponse(result)")
			g.P("}")
			g.P()
		}

		// Close method
		g.P("// Close stops the server")
		g.P("func (s *", serverName, ") Close() error {")
		g.P("	return s.server.Close()")
		g.P("}")
		g.P()
	}
}

func generateCQRSSDK(gen *protogen.Plugin, file *protogen.File, aggregateNames map[string]bool, services []*ServiceInfo) {
	sdkFilename := file.GeneratedFilenamePrefix + "_sdk.cqrs.pb.go"
	g := gen.NewGeneratedFile(sdkFilename, file.GoImportPath)

	// Header
	g.P("// Code generated by protoc-gen-cqrs. DO NOT EDIT.")
	g.P("// version: ", version)
	g.P("// Unified SDK for ", file.Desc.Name())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P()
	g.P(`	"github.com/plaenen/eventstore/pkg/eventsourcing"`)
	g.P(")")
	g.P()

	// Generate SDK for each aggregate
	for aggName := range aggregateNames {
		sdkName := aggName + "SDK"
		clientName := aggName + "Client"

		// SDK documentation
		g.P("// ", sdkName, " provides a unified, developer-friendly interface for the ", aggName, " service.")
		g.P("// It combines all commands and queries into a single client that only requires a transport.")
		g.P("//")
		g.P("// Example usage:")
		g.P("//")
		g.P("//	transport, _ := nats.NewTransport(&nats.TransportConfig{...})")
		g.P("//	sdk := ", file.GoPackageName, ".New", sdkName, "(transport)")
		g.P("//")
		g.P("//	// Execute commands and queries")

		// Find first command as example
		for _, svc := range services {
			if svc.AggregateName == aggName && len(svc.Commands) > 0 {
				firstCmd := svc.Commands[0]
				cmdName := firstCmd.GoName
				g.P("//	resp, err := sdk.", cmdName, "(ctx, &", file.GoPackageName, ".", firstCmd.Input.GoIdent.GoName, "{...})")
				break
			}
		}

		g.P("type ", sdkName, " struct {")
		g.P("	client *", clientName)
		g.P("}")
		g.P()

		// Constructor
		g.P("// New", sdkName, " creates a new unified SDK for the ", aggName, " service.")
		g.P("// It only requires a transport - all service clients are created automatically.")
		g.P("func New", sdkName, "(transport eventsourcing.Transport) *", sdkName, " {")
		g.P("	return &", sdkName, "{")
		g.P("		client: New", clientName, "(transport),")
		g.P("	}")
		g.P("}")
		g.P()

		// Generate wrapper methods for commands and queries
		for _, svc := range services {
			if svc.AggregateName != aggName {
				continue
			}

			// Commands
			if len(svc.Commands) > 0 {
				g.P("// Commands")
				g.P()
			}

			for _, method := range svc.Commands {
				methodName := method.GoName
				inputType := g.QualifiedGoIdent(method.Input.GoIdent)
				outputType := g.QualifiedGoIdent(method.Output.GoIdent)

				// Extract brief description from method name
				description := extractDescription(methodName)

				g.P("// ", methodName, " ", description)
				g.P("func (s *", sdkName, ") ", methodName, "(ctx context.Context, cmd *", inputType, ") (*", outputType, ", *eventsourcing.AppError) {")
				g.P("	return s.client.", methodName, "(ctx, cmd)")
				g.P("}")
				g.P()
			}

			// Queries
			if len(svc.Queries) > 0 {
				g.P("// Queries")
				g.P()
			}

			for _, method := range svc.Queries {
				methodName := method.GoName
				inputType := g.QualifiedGoIdent(method.Input.GoIdent)
				outputType := g.QualifiedGoIdent(method.Output.GoIdent)

				description := extractDescription(methodName)

				g.P("// ", methodName, " ", description)
				g.P("func (s *", sdkName, ") ", methodName, "(ctx context.Context, query *", inputType, ") (*", outputType, ", *eventsourcing.AppError) {")
				g.P("	return s.client.", methodName, "(ctx, query)")
				g.P("}")
				g.P()
			}
		}

		// Utility methods
		g.P("// Transport returns the underlying transport used by this SDK.")
		g.P("// This can be useful for cleanup or advanced use cases.")
		g.P("func (s *", sdkName, ") Transport() eventsourcing.Transport {")
		g.P("	return s.client.transport")
		g.P("}")
		g.P()

		g.P("// Close closes the underlying transport connection.")
		g.P("// This is a convenience method equivalent to calling Transport().Close()")
		g.P("func (s *", sdkName, ") Close() error {")
		g.P("	return s.client.transport.Close()")
		g.P("}")
		g.P()
	}
}

// extractDescription creates a brief description from a method name
func extractDescription(methodName string) string {
	switch {
	case strings.HasPrefix(methodName, "Get"):
		return "retrieves " + strings.ToLower(strings.TrimPrefix(methodName, "Get"))
	case strings.HasPrefix(methodName, "List"):
		return "lists " + strings.ToLower(strings.TrimPrefix(methodName, "List"))
	case strings.HasPrefix(methodName, "Create"):
		return "creates a new " + strings.ToLower(strings.TrimPrefix(methodName, "Create"))
	case strings.HasPrefix(methodName, "Update"):
		return "updates " + strings.ToLower(strings.TrimPrefix(methodName, "Update"))
	case strings.HasPrefix(methodName, "Delete"):
		return "deletes " + strings.ToLower(strings.TrimPrefix(methodName, "Delete"))
	case strings.HasPrefix(methodName, "Open"):
		return "opens " + strings.ToLower(strings.TrimPrefix(methodName, "Open"))
	case strings.HasPrefix(methodName, "Close"):
		return "closes " + strings.ToLower(strings.TrimPrefix(methodName, "Close"))
	case methodName == "Deposit":
		return "adds money to an account"
	case methodName == "Withdraw":
		return "removes money from an account"
	default:
		return "executes " + strings.ToLower(methodName)
	}
}
