// protoc-gen-cqrs generates CQRS infrastructure from proto files.
//
// This plugin generates files with the .cqrs.pb.go extension to clearly indicate
// they are generated by the CQRS plugin (for transport and routing).
//
// Generated files:
//   - *_client.cqrs.pb.go - Unified client SDK with low-level and high-level interfaces
//   - *_server.cqrs.pb.go - Server-side routing, handler interfaces, and request handling
//
// Example usage:
//
//	protoc --go_out=. --cqrs_out=. proto/**/*.proto
//
// Configuration via Proto Options:
//
// The plugin uses custom proto options (defined in cqrs/options.proto):
//
//	Service level (required):
//	 - option (cqrs.service) = {
//	     service_type: SERVICE_TYPE_COMMAND
//	     aggregate_name: "Account"  // Optional: groups related services
//	   }
package main

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/plaenen/eventstore/pkg/cqrs"
)

var version = "0.0.2"

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			generateFile(gen, f)
		}

		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	// Find services with CQRS options
	services := findServices(file)
	if len(services) == 0 {
		return
	}

	// Check if any service wants client generation
	hasClientGeneration := false
	for _, svc := range services {
		opts := getCQRSServiceOptions(svc.Service)
		if opts != nil && opts.GetGenerateClient() {
			hasClientGeneration = true
			break
		}
	}

	// Generate client file (one file per proto file, containing all service clients)
	if hasClientGeneration {
		generateClients(gen, file, services)
	}

	// Always generate server file (contains handler interfaces)
	if hasServiceMethods(services) {
		generateCQRSServer(gen, file, services)
	}
}

// ServiceInfo holds information about CQRS services
type ServiceInfo struct {
	Name     string
	Commands []*protogen.Method
	Queries  []*protogen.Method
	Service  *protogen.Service
}

// Helper functions

func getCQRSServiceOptions(svc *protogen.Service) *cqrs.ServiceOptions {
	if proto.HasExtension(svc.Desc.Options(), cqrs.E_Service) {
		return proto.GetExtension(
			svc.Desc.Options(),
			cqrs.E_Service,
		).(*cqrs.ServiceOptions)
	}
	return nil
}

func hasServiceMethods(services []*ServiceInfo) bool {
	for _, svc := range services {
		if len(svc.Commands) > 0 || len(svc.Queries) > 0 {
			return true
		}
	}
	return false
}

func findServices(file *protogen.File) []*ServiceInfo {
	var services []*ServiceInfo

	for _, svc := range file.Services {
		name := string(svc.Desc.Name())

		// Get CQRS options
		cqrsOpts := getCQRSServiceOptions(svc)
		if cqrsOpts == nil {
			// No CQRS options - skip
			continue
		}

		// Determine service type
		var serviceType string
		switch cqrsOpts.ServiceType {
		case cqrs.ServiceType_SERVICE_TYPE_COMMAND:
			serviceType = "command"
		case cqrs.ServiceType_SERVICE_TYPE_QUERY:
			serviceType = "query"
		case cqrs.ServiceType_SERVICE_TYPE_UNSPECIFIED:
			// Fall back to naming convention
			if strings.HasSuffix(name, "CommandService") {
				serviceType = "command"
			} else if strings.HasSuffix(name, "QueryService") {
				serviceType = "query"
			} else {
				// No type specified - skip
				continue
			}
		default:
			// Unknown type - skip
			continue
		}

		info := &ServiceInfo{
			Name:     name,
			Service:  svc,
			Commands: make([]*protogen.Method, 0),
			Queries:  make([]*protogen.Method, 0),
		}

		// Categorize methods
		for _, method := range svc.Methods {
			if serviceType == "command" {
				info.Commands = append(info.Commands, method)
			} else if serviceType == "query" {
				info.Queries = append(info.Queries, method)
			}
		}

		services = append(services, info)
	}

	return services
}

func generateClients(gen *protogen.Plugin, file *protogen.File, services []*ServiceInfo) {
	clientFilename := file.GeneratedFilenamePrefix + "_client.cqrs.pb.go"
	g := gen.NewGeneratedFile(clientFilename, file.GoImportPath)

	// Header
	g.P("// Code generated by protoc-gen-cqrs. DO NOT EDIT.")
	g.P("// version: ", version)
	g.P("// CQRS Clients for ", file.Desc.Name())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"fmt"`)
	g.P()
	g.P(`	"github.com/plaenen/eventstore/pkg/cqrs"`)
	g.P(")")
	g.P()

	// Generate one client per service
	for _, svc := range services {
		opts := getCQRSServiceOptions(svc.Service)
		if opts == nil || !opts.GetGenerateClient() {
			continue // Skip if client generation not requested
		}

		clientName := "Cqrs" + svc.Name + "Client"

		// Client struct
		g.P("// ", clientName, " provides type-safe client methods for ", svc.Name)
		g.P("type ", clientName, " struct {")
		g.P("	transport      cqrs.Transport")
		g.P("	subjectBuilder cqrs.SubjectBuilder")
		g.P("}")
		g.P()

		// Private setter for SubjectBuilder (used by shared ClientOption)
		g.P("func (c *", clientName, ") setSubjectBuilder(builder cqrs.SubjectBuilder) {")
		g.P("	c.subjectBuilder = builder")
		g.P("}")
		g.P()

		// Constructor
		g.P("// New", clientName, " creates a new client for ", svc.Name, ".")
		g.P("// By default, uses DefaultSubjectBuilder which creates subjects in the format:")
		g.P("//   package.service.method (e.g., \"account.v1.AccountService.OpenAccount\")")
		g.P("//")
		g.P("// Options:")
		g.P("//   - cqrs.WithClientSubjectBuilder: Use a custom SubjectBuilder for dynamic subject routing")
		g.P("func New", clientName, "(transport cqrs.Transport, opts ...cqrs.ClientOption) *", clientName, " {")
		g.P("	c := &", clientName, "{")
		g.P("		transport:      transport,")
		g.P("		subjectBuilder: &cqrs.DefaultSubjectBuilder{},")
		g.P("	}")
		g.P("	for _, opt := range opts {")
		g.P("		opt(c)")
		g.P("	}")
		g.P("	return c")
		g.P("}")
		g.P()

		// Generate command methods
		for _, method := range svc.Commands {
			methodName := method.GoName
			inputType := g.QualifiedGoIdent(method.Input.GoIdent)
			outputType := g.QualifiedGoIdent(method.Output.GoIdent)
			packageName := string(file.Desc.Package())

			g.P("// ", methodName, " sends a ", methodName, " command and returns the response.")
			g.P("// Returns (result, nil) on success or (nil, error) on failure.")
			g.P("func (c *", clientName, ") ", methodName, "(ctx context.Context, cmd *", inputType, ") (*", outputType, ", error) {")
			g.P("	// Build subject using SubjectBuilder")
			g.P(`	subject := c.subjectBuilder.BuildSubject(ctx, "`, packageName, `", "`, svc.Name, `", "`, methodName, `")`)
			g.P()
			g.P("	// Send request via transport - returns (proto.Message, error)")
			g.P(`	respMsg, err := c.transport.Request(ctx, subject, cmd)`)
			g.P("	if err != nil {")
			g.P("		return nil, err")
			g.P("	}")
			g.P()
			g.P("	// Type-assert to expected response type")
			g.P("	result, ok := respMsg.(*", outputType, ")")
			g.P("	if !ok {")
			g.P(`		return nil, fmt.Errorf("unexpected response type: %T", respMsg)`)
			g.P("	}")
			g.P()
			g.P("	return result, nil")
			g.P("}")
			g.P()
		}

		// Generate query methods
		for _, method := range svc.Queries {
			methodName := method.GoName
			inputType := g.QualifiedGoIdent(method.Input.GoIdent)
			outputType := g.QualifiedGoIdent(method.Output.GoIdent)
			packageName := string(file.Desc.Package())

			g.P("// ", methodName, " executes a ", methodName, " query and returns the result.")
			g.P("// Returns (result, nil) on success or (nil, error) on failure.")
			g.P("func (c *", clientName, ") ", methodName, "(ctx context.Context, query *", inputType, ") (*", outputType, ", error) {")
			g.P("	// Build subject using SubjectBuilder")
			g.P(`	subject := c.subjectBuilder.BuildSubject(ctx, "`, packageName, `", "`, svc.Name, `", "`, methodName, `")`)
			g.P()
			g.P("	// Send request via transport - returns (proto.Message, error)")
			g.P(`	respMsg, err := c.transport.Request(ctx, subject, query)`)
			g.P("	if err != nil {")
			g.P("		return nil, err")
			g.P("	}")
			g.P()
			g.P("	// Type-assert to expected response type")
			g.P("	result, ok := respMsg.(*", outputType, ")")
			g.P("	if !ok {")
			g.P(`		return nil, fmt.Errorf("unexpected response type: %T", respMsg)`)
			g.P("	}")
			g.P()
			g.P("	return result, nil")
			g.P("}")
			g.P()
		}
	}
}

func generateCQRSServer(gen *protogen.Plugin, file *protogen.File, services []*ServiceInfo) {
	serverFilename := file.GeneratedFilenamePrefix + "_server.cqrs.pb.go"
	g := gen.NewGeneratedFile(serverFilename, file.GoImportPath)

	// Header
	g.P("// Code generated by protoc-gen-cqrs. DO NOT EDIT.")
	g.P("// version: ", version)
	g.P("// Server service for ", file.Desc.Name())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"fmt"`)
	g.P()
	g.P(`	"github.com/plaenen/eventstore/pkg/cqrs"`)
	g.P(`	"google.golang.org/protobuf/proto"`)
	g.P(")")
	g.P()

	// Generate handler interfaces and servers for each service
	for _, svc := range services {
		serverName := "Cqrs" + svc.Name + "Server"
		handlerName := "Cqrs" + svc.Name + "Handler"

		// Generate handler interface
		g.P("// ", handlerName, " defines the business logic for ", svc.Name)
		g.P("type ", handlerName, " interface {")

		// Add methods for commands
		for _, method := range svc.Commands {
			methodName := method.GoName
			inputType := g.QualifiedGoIdent(method.Input.GoIdent)
			outputType := g.QualifiedGoIdent(method.Output.GoIdent)
			g.P("	", methodName, "(ctx context.Context, cmd *", inputType, ") (*", outputType, ", error)")
		}

		// Add methods for queries
		for _, method := range svc.Queries {
			methodName := method.GoName
			inputType := g.QualifiedGoIdent(method.Input.GoIdent)
			outputType := g.QualifiedGoIdent(method.Output.GoIdent)
			g.P("	", methodName, "(ctx context.Context, query *", inputType, ") (*", outputType, ", error)")
		}

		g.P("}")
		g.P()

		// Server struct
		g.P("// ", serverName, " routes requests to the ", handlerName, " implementation")
		g.P("type ", serverName, " struct {")
		g.P("	server  cqrs.Server")
		g.P("	handler ", handlerName)
		g.P("}")
		g.P()

		// Constructor
		g.P("// New", serverName, " creates a new server")
		g.P("func New", serverName, "(server cqrs.Server, handler ", handlerName, ") *", serverName, " {")
		g.P("	return &", serverName, "{")
		g.P("		server:  server,")
		g.P("		handler: handler,")
		g.P("	}")
		g.P("}")
		g.P()

		// Start method
		g.P("// Start registers handlers and starts the server")
		g.P("func (s *", serverName, ") Start(ctx context.Context) error {")

		// Register handlers for commands
		for _, method := range svc.Commands {
			methodName := method.GoName
			subject := string(file.Desc.Package()) + "." + svc.Name + "." + methodName

			g.P(`	if err := s.server.RegisterHandler("`, subject, `", s.handle`, methodName, `); err != nil {`)
			g.P("		return fmt.Errorf(\"failed to register ", methodName, ": %w\", err)")
			g.P("	}")
		}

		// Register handlers for queries
		for _, method := range svc.Queries {
			methodName := method.GoName
			subject := string(file.Desc.Package()) + "." + svc.Name + "." + methodName

			g.P(`	if err := s.server.RegisterHandler("`, subject, `", s.handle`, methodName, `); err != nil {`)
			g.P("		return fmt.Errorf(\"failed to register ", methodName, ": %w\", err)")
			g.P("	}")
		}

		g.P()
		g.P("	return s.server.Start(ctx)")
		g.P("}")
		g.P()

		// Generate handler wrapper methods for commands
		for _, method := range svc.Commands {
			methodName := method.GoName
			inputType := g.QualifiedGoIdent(method.Input.GoIdent)

			g.P("// handle", methodName, " is the internal handler wrapper for ", methodName)
			g.P("func (s *", serverName, ") handle", methodName, "(ctx context.Context, request proto.Message) (proto.Message, error) {")
			g.P("	req := request.(*", inputType, ")")
			g.P("	result, err := s.handler.", methodName, "(ctx, req)")
			g.P("	if err != nil {")
			g.P("		return nil, err")
			g.P("	}")
			g.P("	return result, nil")
			g.P("}")
			g.P()
		}

		// Generate handler wrapper methods for queries
		for _, method := range svc.Queries {
			methodName := method.GoName
			inputType := g.QualifiedGoIdent(method.Input.GoIdent)

			g.P("// handle", methodName, " is the internal handler wrapper for ", methodName)
			g.P("func (s *", serverName, ") handle", methodName, "(ctx context.Context, request proto.Message) (proto.Message, error) {")
			g.P("	req := request.(*", inputType, ")")
			g.P("	result, err := s.handler.", methodName, "(ctx, req)")
			g.P("	if err != nil {")
			g.P("		return nil, err")
			g.P("	}")
			g.P("	return result, nil")
			g.P("}")
			g.P()
		}

		// Close method
		g.P("// Close stops the server")
		g.P("func (s *", serverName, ") Close() error {")
		g.P("	return s.server.Close()")
		g.P("}")
		g.P()
	}
}

// extractDescription creates a brief description from a method name
func extractDescription(methodName string) string {
	switch {
	case strings.HasPrefix(methodName, "Get"):
		return "retrieves " + strings.ToLower(strings.TrimPrefix(methodName, "Get"))
	case strings.HasPrefix(methodName, "List"):
		return "lists " + strings.ToLower(strings.TrimPrefix(methodName, "List"))
	case strings.HasPrefix(methodName, "Create"):
		return "creates a new " + strings.ToLower(strings.TrimPrefix(methodName, "Create"))
	case strings.HasPrefix(methodName, "Update"):
		return "updates " + strings.ToLower(strings.TrimPrefix(methodName, "Update"))
	case strings.HasPrefix(methodName, "Delete"):
		return "deletes " + strings.ToLower(strings.TrimPrefix(methodName, "Delete"))
	case strings.HasPrefix(methodName, "Open"):
		return "opens " + strings.ToLower(strings.TrimPrefix(methodName, "Open"))
	case strings.HasPrefix(methodName, "Close"):
		return "closes " + strings.ToLower(strings.TrimPrefix(methodName, "Close"))
	case methodName == "Deposit":
		return "adds money to an account"
	case methodName == "Withdraw":
		return "removes money from an account"
	default:
		return "executes " + strings.ToLower(methodName)
	}
}
