// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metadata.sql

package sqlcgen

import (
	"context"
)

const deleteAllMetadata = `-- name: DeleteAllMetadata :exec
DELETE FROM projection_metadata
WHERE projection_name = ?
`

func (q *Queries) DeleteAllMetadata(ctx context.Context, projectionName string) error {
	_, err := q.exec(ctx, q.deleteAllMetadataStmt, deleteAllMetadata, projectionName)
	return err
}

const deleteMetadata = `-- name: DeleteMetadata :exec
DELETE FROM projection_metadata
WHERE projection_name = ? AND key = ?
`

type DeleteMetadataParams struct {
	ProjectionName string `json:"projection_name"`
	Key            string `json:"key"`
}

func (q *Queries) DeleteMetadata(ctx context.Context, arg DeleteMetadataParams) error {
	_, err := q.exec(ctx, q.deleteMetadataStmt, deleteMetadata, arg.ProjectionName, arg.Key)
	return err
}

const getAllMetadata = `-- name: GetAllMetadata :many
SELECT key, value
FROM projection_metadata
WHERE projection_name = ?
ORDER BY key
`

type GetAllMetadataRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetAllMetadata(ctx context.Context, projectionName string) ([]GetAllMetadataRow, error) {
	rows, err := q.query(ctx, q.getAllMetadataStmt, getAllMetadata, projectionName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllMetadataRow{}
	for rows.Next() {
		var i GetAllMetadataRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetadata = `-- name: GetMetadata :one
SELECT value
FROM projection_metadata
WHERE projection_name = ? AND key = ?
`

type GetMetadataParams struct {
	ProjectionName string `json:"projection_name"`
	Key            string `json:"key"`
}

func (q *Queries) GetMetadata(ctx context.Context, arg GetMetadataParams) (string, error) {
	row := q.queryRow(ctx, q.getMetadataStmt, getMetadata, arg.ProjectionName, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listProjectionsWithMetadata = `-- name: ListProjectionsWithMetadata :many
SELECT DISTINCT projection_name
FROM projection_metadata
ORDER BY projection_name
`

func (q *Queries) ListProjectionsWithMetadata(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listProjectionsWithMetadataStmt, listProjectionsWithMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var projection_name string
		if err := rows.Scan(&projection_name); err != nil {
			return nil, err
		}
		items = append(items, projection_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMetadata = `-- name: SetMetadata :exec
INSERT INTO projection_metadata (projection_name, key, value, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(projection_name, key) DO UPDATE SET
    value = excluded.value,
    updated_at = excluded.updated_at
`

type SetMetadataParams struct {
	ProjectionName string `json:"projection_name"`
	Key            string `json:"key"`
	Value          string `json:"value"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) SetMetadata(ctx context.Context, arg SetMetadataParams) error {
	_, err := q.exec(ctx, q.setMetadataStmt, setMetadata,
		arg.ProjectionName,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}
