// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Event struct {
	EventID       string         `json:"event_id"`
	AggregateID   string         `json:"aggregate_id"`
	AggregateType string         `json:"aggregate_type"`
	EventType     string         `json:"event_type"`
	Version       int64          `json:"version"`
	Timestamp     int64          `json:"timestamp"`
	Data          []byte         `json:"data"`
	Metadata      string         `json:"metadata"`
	Constraints   sql.NullString `json:"constraints"`
	Position      sql.NullInt64  `json:"position"`
}

type ProcessedCommand struct {
	CommandID   string `json:"command_id"`
	AggregateID string `json:"aggregate_id"`
	ProcessedAt int64  `json:"processed_at"`
	ExpiresAt   int64  `json:"expires_at"`
	EventIds    string `json:"event_ids"`
}

type ProjectionCheckpoint struct {
	ProjectionName string `json:"projection_name"`
	Position       int64  `json:"position"`
	LastEventID    string `json:"last_event_id"`
	UpdatedAt      int64  `json:"updated_at"`
}

type Snapshot struct {
	AggregateID   string         `json:"aggregate_id"`
	AggregateType string         `json:"aggregate_type"`
	Version       int64          `json:"version"`
	Data          []byte         `json:"data"`
	CreatedAt     int64          `json:"created_at"`
	Metadata      sql.NullString `json:"metadata"`
}

type UniqueConstraint struct {
	IndexName   string `json:"index_name"`
	Value       string `json:"value"`
	AggregateID string `json:"aggregate_id"`
	CreatedAt   int64  `json:"created_at"`
}
