// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CheckCommandExists(ctx context.Context, commandID string) (string, error)
	ClaimConstraint(ctx context.Context, arg ClaimConstraintParams) error
	CleanExpiredCommands(ctx context.Context, expiresAt int64) (int64, error)
	CountSnapshotsForAggregate(ctx context.Context, aggregateID string) (int64, error)
	DeleteAllConstraints(ctx context.Context) error
	DeleteCheckpoint(ctx context.Context, projectionName string) error
	// Deletes snapshots older than a specific version for an aggregate
	DeleteOldSnapshots(ctx context.Context, arg DeleteOldSnapshotsParams) error
	DeleteSnapshotsOlderThan(ctx context.Context, createdAt int64) error
	GetAggregateVersion(ctx context.Context, aggregateID string) (interface{}, error)
	GetAllConstraints(ctx context.Context) ([]GetAllConstraintsRow, error)
	GetConstraintOwner(ctx context.Context, arg GetConstraintOwnerParams) (string, error)
	GetLatestSnapshot(ctx context.Context, aggregateID string) (Snapshot, error)
	GetLatestSnapshotBeforeVersion(ctx context.Context, arg GetLatestSnapshotBeforeVersionParams) (Snapshot, error)
	GetProcessedCommand(ctx context.Context, arg GetProcessedCommandParams) (GetProcessedCommandRow, error)
	GetSnapshotAtVersion(ctx context.Context, arg GetSnapshotAtVersionParams) (Snapshot, error)
	GetSnapshotStats(ctx context.Context) (GetSnapshotStatsRow, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertProcessedCommand(ctx context.Context, arg InsertProcessedCommandParams) error
	ListSnapshotsForAggregate(ctx context.Context, aggregateID string) ([]Snapshot, error)
	LoadAllEvents(ctx context.Context, arg LoadAllEventsParams) ([]Event, error)
	LoadCheckpoint(ctx context.Context, projectionName string) (ProjectionCheckpoint, error)
	LoadEventByID(ctx context.Context, eventID string) (LoadEventByIDRow, error)
	LoadEvents(ctx context.Context, arg LoadEventsParams) ([]LoadEventsRow, error)
	ReleaseConstraint(ctx context.Context, arg ReleaseConstraintParams) error
	SaveCheckpoint(ctx context.Context, arg SaveCheckpointParams) error
	SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) error
	UpdateEventPositions(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
