// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: subscription/v1/events.proto

package subscriptionv1

import (
	_ "github.com/plaenen/eventstore/pkg/eventsourcing"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionCreatedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	AdminEmail     string                 `protobuf:"bytes,2,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionCreatedEvent) Reset() {
	*x = SubscriptionCreatedEvent{}
	mi := &file_subscription_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionCreatedEvent) ProtoMessage() {}

func (x *SubscriptionCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionCreatedEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionCreatedEvent) Descriptor() ([]byte, []int) {
	return file_subscription_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionCreatedEvent) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscriptionCreatedEvent) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *SubscriptionCreatedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SubscriptionCancelledEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Timestamp      int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionCancelledEvent) Reset() {
	*x = SubscriptionCancelledEvent{}
	mi := &file_subscription_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionCancelledEvent) ProtoMessage() {}

func (x *SubscriptionCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionCancelledEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionCancelledEvent) Descriptor() ([]byte, []int) {
	return file_subscription_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *SubscriptionCancelledEvent) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscriptionCancelledEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_subscription_v1_events_proto protoreflect.FileDescriptor

const file_subscription_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1csubscription/v1/events.proto\x12\x0fsubscription.v1\x1a\x1beventsourcing/options.proto\"\x96\x01\n" +
	"\x18SubscriptionCreatedEvent\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1f\n" +
	"\vadmin_email\x18\x02 \x01(\tR\n" +
	"adminEmail\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp:\x12\xa2\xb5\x18\x0e\n" +
	"\fSubscription\"w\n" +
	"\x1aSubscriptionCancelledEvent\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp:\x12\xa2\xb5\x18\x0e\n" +
	"\fSubscriptionB\xc9\x01\n" +
	"\x13com.subscription.v1B\vEventsProtoP\x01ZHgithub.com/plaenen/eventstore/examples/pb/subscription/v1;subscriptionv1\xa2\x02\x03SXX\xaa\x02\x0fSubscription.V1\xca\x02\x0fSubscription\\V1\xe2\x02\x1bSubscription\\V1\\GPBMetadata\xea\x02\x10Subscription::V1b\x06proto3"

var (
	file_subscription_v1_events_proto_rawDescOnce sync.Once
	file_subscription_v1_events_proto_rawDescData []byte
)

func file_subscription_v1_events_proto_rawDescGZIP() []byte {
	file_subscription_v1_events_proto_rawDescOnce.Do(func() {
		file_subscription_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_v1_events_proto_rawDesc), len(file_subscription_v1_events_proto_rawDesc)))
	})
	return file_subscription_v1_events_proto_rawDescData
}

var file_subscription_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subscription_v1_events_proto_goTypes = []any{
	(*SubscriptionCreatedEvent)(nil),   // 0: subscription.v1.SubscriptionCreatedEvent
	(*SubscriptionCancelledEvent)(nil), // 1: subscription.v1.SubscriptionCancelledEvent
}
var file_subscription_v1_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subscription_v1_events_proto_init() }
func file_subscription_v1_events_proto_init() {
	if File_subscription_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_v1_events_proto_rawDesc), len(file_subscription_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscription_v1_events_proto_goTypes,
		DependencyIndexes: file_subscription_v1_events_proto_depIdxs,
		MessageInfos:      file_subscription_v1_events_proto_msgTypes,
	}.Build()
	File_subscription_v1_events_proto = out.File
	file_subscription_v1_events_proto_goTypes = nil
	file_subscription_v1_events_proto_depIdxs = nil
}
