// Code generated by protoc-gen-eventsourcing. DO NOT EDIT.
// version: 0.0.21
// Server service for v1

package subscriptionv1

import (
	"context"
	"fmt"

	"github.com/plaenen/eventstore/pkg/eventsourcing"
	"google.golang.org/protobuf/proto"
)

// SubscriptionCommandServiceServer routes requests to the SubscriptionCommandServiceHandler implementation
type SubscriptionCommandServiceServer struct {
	server  eventsourcing.Server
	handler SubscriptionCommandServiceHandler
}

// NewSubscriptionCommandServiceServer creates a new server
func NewSubscriptionCommandServiceServer(server eventsourcing.Server, handler SubscriptionCommandServiceHandler) *SubscriptionCommandServiceServer {
	return &SubscriptionCommandServiceServer{
		server:  server,
		handler: handler,
	}
}

// Start registers handlers and starts the server
func (s *SubscriptionCommandServiceServer) Start(ctx context.Context) error {
	if err := s.server.RegisterHandler("subscription.v1.SubscriptionCommandService.CreateSubscription", s.handleCreateSubscription); err != nil {
		return fmt.Errorf("failed to register CreateSubscription: %w", err)
	}
	if err := s.server.RegisterHandler("subscription.v1.SubscriptionCommandService.CancelSubscription", s.handleCancelSubscription); err != nil {
		return fmt.Errorf("failed to register CancelSubscription: %w", err)
	}

	return s.server.Start(ctx)
}

func (s *SubscriptionCommandServiceServer) handleCreateSubscription(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*CreateSubscriptionCommand)
	result, appErr := s.handler.CreateSubscription(ctx, req)
	if appErr != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   appErr,
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *SubscriptionCommandServiceServer) handleCancelSubscription(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*CancelSubscriptionCommand)
	result, appErr := s.handler.CancelSubscription(ctx, req)
	if appErr != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   appErr,
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

// Close stops the server
func (s *SubscriptionCommandServiceServer) Close() error {
	return s.server.Close()
}
