// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type IdentitySeed struct {
	ID        string    `json:"id"`
	Seed      string    `json:"seed"`
	CreatedAt time.Time `json:"created_at"`
}
