// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetSeed(ctx context.Context, id string) (string, error)
	SaveSeed(ctx context.Context, arg SaveSeedParams) error
}

var _ Querier = (*Queries)(nil)
