run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - examples/pb
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.connect\\.go$"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - exportloopref
    - gocyclo
    - goimports
    - misspell
    - unparam
    - unconvert
    - goconst
    - prealloc
    - nakedret
    - gocritic
    - godot
    - whitespace
    - wsl
    - revive
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - checkPrivateReceivers
          - disableStutteringCheck

  gosec:
    excludes:
      - G404 # Use of weak random number generator (we use it for IDs, not crypto)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude generated files
    - path: ".*\\.pb\\.go$"
      linters:
        - all

    - path: ".*\\.connect\\.go$"
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
