// Code generated by protoc-gen-cqrs. DO NOT EDIT.
// version: 0.0.1
// CQRS Clients for v1

package accountv1

import (
	"context"
	"fmt"

	"github.com/plaenen/eventstore/pkg/cqrs"
)

// CqrsAccountCommandServiceClient provides type-safe client methods for AccountCommandService
type CqrsAccountCommandServiceClient struct {
	transport      cqrs.Transport
	subjectBuilder cqrs.SubjectBuilder
}

func (c *CqrsAccountCommandServiceClient) setSubjectBuilder(builder cqrs.SubjectBuilder) {
	c.subjectBuilder = builder
}

// NewCqrsAccountCommandServiceClient creates a new client for AccountCommandService.
// By default, uses DefaultSubjectBuilder which creates subjects in the format:
//
//	package.service.method (e.g., "account.v1.AccountService.OpenAccount")
//
// Options:
//   - cqrs.WithClientSubjectBuilder: Use a custom SubjectBuilder for dynamic subject routing
func NewCqrsAccountCommandServiceClient(transport cqrs.Transport, opts ...cqrs.ClientOption) *CqrsAccountCommandServiceClient {
	c := &CqrsAccountCommandServiceClient{
		transport:      transport,
		subjectBuilder: &cqrs.DefaultSubjectBuilder{},
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// OpenAccount sends a OpenAccount command and returns the response.
// Returns (result, nil) on success or (nil, error) on failure.
func (c *CqrsAccountCommandServiceClient) OpenAccount(ctx context.Context, cmd *OpenAccountCommand) (*OpenAccountResponse, error) {
	// Build subject using SubjectBuilder
	subject := c.subjectBuilder.BuildSubject(ctx, "account.v1", "AccountCommandService", "OpenAccount")

	// Send request via transport - returns (proto.Message, error)
	respMsg, err := c.transport.Request(ctx, subject, cmd)
	if err != nil {
		return nil, err
	}

	// Type-assert to expected response type
	result, ok := respMsg.(*OpenAccountResponse)
	if !ok {
		return nil, fmt.Errorf("unexpected response type: %T", respMsg)
	}

	return result, nil
}

// Deposit sends a Deposit command and returns the response.
// Returns (result, nil) on success or (nil, error) on failure.
func (c *CqrsAccountCommandServiceClient) Deposit(ctx context.Context, cmd *DepositCommand) (*DepositResponse, error) {
	// Build subject using SubjectBuilder
	subject := c.subjectBuilder.BuildSubject(ctx, "account.v1", "AccountCommandService", "Deposit")

	// Send request via transport - returns (proto.Message, error)
	respMsg, err := c.transport.Request(ctx, subject, cmd)
	if err != nil {
		return nil, err
	}

	// Type-assert to expected response type
	result, ok := respMsg.(*DepositResponse)
	if !ok {
		return nil, fmt.Errorf("unexpected response type: %T", respMsg)
	}

	return result, nil
}

// Withdraw sends a Withdraw command and returns the response.
// Returns (result, nil) on success or (nil, error) on failure.
func (c *CqrsAccountCommandServiceClient) Withdraw(ctx context.Context, cmd *WithdrawCommand) (*WithdrawResponse, error) {
	// Build subject using SubjectBuilder
	subject := c.subjectBuilder.BuildSubject(ctx, "account.v1", "AccountCommandService", "Withdraw")

	// Send request via transport - returns (proto.Message, error)
	respMsg, err := c.transport.Request(ctx, subject, cmd)
	if err != nil {
		return nil, err
	}

	// Type-assert to expected response type
	result, ok := respMsg.(*WithdrawResponse)
	if !ok {
		return nil, fmt.Errorf("unexpected response type: %T", respMsg)
	}

	return result, nil
}

// CloseAccount sends a CloseAccount command and returns the response.
// Returns (result, nil) on success or (nil, error) on failure.
func (c *CqrsAccountCommandServiceClient) CloseAccount(ctx context.Context, cmd *CloseAccountCommand) (*CloseAccountResponse, error) {
	// Build subject using SubjectBuilder
	subject := c.subjectBuilder.BuildSubject(ctx, "account.v1", "AccountCommandService", "CloseAccount")

	// Send request via transport - returns (proto.Message, error)
	respMsg, err := c.transport.Request(ctx, subject, cmd)
	if err != nil {
		return nil, err
	}

	// Type-assert to expected response type
	result, ok := respMsg.(*CloseAccountResponse)
	if !ok {
		return nil, fmt.Errorf("unexpected response type: %T", respMsg)
	}

	return result, nil
}

// CqrsAccountQueryServiceClient provides type-safe client methods for AccountQueryService
type CqrsAccountQueryServiceClient struct {
	transport      cqrs.Transport
	subjectBuilder cqrs.SubjectBuilder
}

func (c *CqrsAccountQueryServiceClient) setSubjectBuilder(builder cqrs.SubjectBuilder) {
	c.subjectBuilder = builder
}

// NewCqrsAccountQueryServiceClient creates a new client for AccountQueryService.
// By default, uses DefaultSubjectBuilder which creates subjects in the format:
//
//	package.service.method (e.g., "account.v1.AccountService.OpenAccount")
//
// Options:
//   - cqrs.WithClientSubjectBuilder: Use a custom SubjectBuilder for dynamic subject routing
func NewCqrsAccountQueryServiceClient(transport cqrs.Transport, opts ...cqrs.ClientOption) *CqrsAccountQueryServiceClient {
	c := &CqrsAccountQueryServiceClient{
		transport:      transport,
		subjectBuilder: &cqrs.DefaultSubjectBuilder{},
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// GetAccount executes a GetAccount query and returns the result.
// Returns (result, nil) on success or (nil, error) on failure.
func (c *CqrsAccountQueryServiceClient) GetAccount(ctx context.Context, query *GetAccountRequest) (*AccountView, error) {
	// Build subject using SubjectBuilder
	subject := c.subjectBuilder.BuildSubject(ctx, "account.v1", "AccountQueryService", "GetAccount")

	// Send request via transport - returns (proto.Message, error)
	respMsg, err := c.transport.Request(ctx, subject, query)
	if err != nil {
		return nil, err
	}

	// Type-assert to expected response type
	result, ok := respMsg.(*AccountView)
	if !ok {
		return nil, fmt.Errorf("unexpected response type: %T", respMsg)
	}

	return result, nil
}

// ListAccounts executes a ListAccounts query and returns the result.
// Returns (result, nil) on success or (nil, error) on failure.
func (c *CqrsAccountQueryServiceClient) ListAccounts(ctx context.Context, query *ListAccountsRequest) (*ListAccountsResponse, error) {
	// Build subject using SubjectBuilder
	subject := c.subjectBuilder.BuildSubject(ctx, "account.v1", "AccountQueryService", "ListAccounts")

	// Send request via transport - returns (proto.Message, error)
	respMsg, err := c.transport.Request(ctx, subject, query)
	if err != nil {
		return nil, err
	}

	// Type-assert to expected response type
	result, ok := respMsg.(*ListAccountsResponse)
	if !ok {
		return nil, fmt.Errorf("unexpected response type: %T", respMsg)
	}

	return result, nil
}

// GetAccountBalance executes a GetAccountBalance query and returns the result.
// Returns (result, nil) on success or (nil, error) on failure.
func (c *CqrsAccountQueryServiceClient) GetAccountBalance(ctx context.Context, query *GetAccountBalanceRequest) (*BalanceView, error) {
	// Build subject using SubjectBuilder
	subject := c.subjectBuilder.BuildSubject(ctx, "account.v1", "AccountQueryService", "GetAccountBalance")

	// Send request via transport - returns (proto.Message, error)
	respMsg, err := c.transport.Request(ctx, subject, query)
	if err != nil {
		return nil, err
	}

	// Type-assert to expected response type
	result, ok := respMsg.(*BalanceView)
	if !ok {
		return nil, fmt.Errorf("unexpected response type: %T", respMsg)
	}

	return result, nil
}

// GetAccountHistory executes a GetAccountHistory query and returns the result.
// Returns (result, nil) on success or (nil, error) on failure.
func (c *CqrsAccountQueryServiceClient) GetAccountHistory(ctx context.Context, query *GetAccountHistoryRequest) (*AccountHistoryResponse, error) {
	// Build subject using SubjectBuilder
	subject := c.subjectBuilder.BuildSubject(ctx, "account.v1", "AccountQueryService", "GetAccountHistory")

	// Send request via transport - returns (proto.Message, error)
	respMsg, err := c.transport.Request(ctx, subject, query)
	if err != nil {
		return nil, err
	}

	// Type-assert to expected response type
	result, ok := respMsg.(*AccountHistoryResponse)
	if !ok {
		return nil, fmt.Errorf("unexpected response type: %T", respMsg)
	}

	return result, nil
}
