// Code generated by protoc-gen-eventsourcing. DO NOT EDIT.
// This file provides event sourcing helpers for account.v1 events.

package accountv1

import (
	"context"

	"github.com/plaenen/eventstore/pkg/eventsourcing"
	"google.golang.org/protobuf/proto"
)

// AccountEventApplier is the interface for applying events to an Account aggregate.
// Implement this interface in your domain package to define how events modify state.
type AccountEventApplier interface {
	ApplyAccountOpenedEvent(agg *AccountAggregate, e *AccountOpenedEvent) error
	ApplyMoneyDepositedEvent(agg *AccountAggregate, e *MoneyDepositedEvent) error
	ApplyMoneyWithdrawnEvent(agg *AccountAggregate, e *MoneyWithdrawnEvent) error
	ApplyAccountClosedEvent(agg *AccountAggregate, e *AccountClosedEvent) error
}

// AccountAggregate wraps the Account state with event sourcing capabilities.
type AccountAggregate struct {
	*Account
	applier AccountEventApplier
	events  []*eventsourcing.Event
	version int64
}

// NewAccount creates a new AccountAggregate with the given ID and applier.
func NewAccount(id string, applier AccountEventApplier) *AccountAggregate {
	return &AccountAggregate{
		Account: &Account{AccountId: id},
		applier: applier,
		events:  make([]*eventsourcing.Event, 0),
	}
}

// AggregateID returns the aggregate ID.
func (a *AccountAggregate) AggregateID() string {
	return a.Account.AccountId
}

// AggregateType returns the aggregate type name.
func (a *AccountAggregate) AggregateType() string {
	return "Account"
}

// Version returns the current version.
func (a *AccountAggregate) Version() int64 {
	return a.version
}

// SetVersion sets the version (used during rehydration).
func (a *AccountAggregate) SetVersion(v int64) {
	a.version = v
}

// Events returns uncommitted events.
func (a *AccountAggregate) Events() []*eventsourcing.Event {
	return a.events
}

// ClearEvents clears uncommitted events after persistence.
func (a *AccountAggregate) ClearEvents() {
	a.events = make([]*eventsourcing.Event, 0)
}

// Apply applies an event to the aggregate state.
func (a *AccountAggregate) Apply(event *eventsourcing.Event) error {
	switch event.EventType {
	case AccountOpenedEventType:
		e := &AccountOpenedEvent{}
		if err := proto.Unmarshal(event.Data, e); err != nil {
			return err
		}
		return a.applier.ApplyAccountOpenedEvent(a, e)
	case MoneyDepositedEventType:
		e := &MoneyDepositedEvent{}
		if err := proto.Unmarshal(event.Data, e); err != nil {
			return err
		}
		return a.applier.ApplyMoneyDepositedEvent(a, e)
	case MoneyWithdrawnEventType:
		e := &MoneyWithdrawnEvent{}
		if err := proto.Unmarshal(event.Data, e); err != nil {
			return err
		}
		return a.applier.ApplyMoneyWithdrawnEvent(a, e)
	case AccountClosedEventType:
		e := &AccountClosedEvent{}
		if err := proto.Unmarshal(event.Data, e); err != nil {
			return err
		}
		return a.applier.ApplyAccountClosedEvent(a, e)
	}
	return nil
}

// RaiseEvent raises a new event (to be persisted).
func (a *AccountAggregate) RaiseEvent(eventType string, data proto.Message) error {
	dataBytes, err := proto.Marshal(data)
	if err != nil {
		return err
	}

	event := &eventsourcing.Event{
		ID:            eventsourcing.GenerateID(),
		AggregateID:   a.AggregateID(),
		AggregateType: a.AggregateType(),
		EventType:     eventType,
		Version:       a.version + 1,
		Data:          dataBytes,
	}

	// Apply the event to update state
	if err := a.Apply(event); err != nil {
		return err
	}

	// Add to uncommitted events
	a.events = append(a.events, event)
	a.version++

	return nil
}

// State returns the underlying Account state (for snapshots).
func (a *AccountAggregate) State() proto.Message {
	return a.Account
}

// SetState sets the underlying Account state (for snapshot restoration).
func (a *AccountAggregate) SetState(state proto.Message) {
	if acc, ok := state.(*Account); ok {
		a.Account = acc
	}
}

// ApplyOption is a functional option for Apply methods.
type ApplyOption func(*applyOptions)

type applyOptions struct {
	constraints []eventsourcing.UniqueConstraint
}

// WithUniqueConstraints adds unique constraints to the event.
func WithUniqueConstraints(constraints ...eventsourcing.UniqueConstraint) ApplyOption {
	return func(opts *applyOptions) {
		opts.constraints = append(opts.constraints, constraints...)
	}
}

// ApplyAccountOpenedEvent applies an AccountOpenedEvent with type safety.
func (a *AccountAggregate) ApplyAccountOpenedEvent(e *AccountOpenedEvent, opts ...ApplyOption) error {
	return a.RaiseEvent(AccountOpenedEventType, e)
}

// ApplyMoneyDepositedEvent applies a MoneyDepositedEvent with type safety.
func (a *AccountAggregate) ApplyMoneyDepositedEvent(e *MoneyDepositedEvent, opts ...ApplyOption) error {
	return a.RaiseEvent(MoneyDepositedEventType, e)
}

// ApplyMoneyWithdrawnEvent applies a MoneyWithdrawnEvent with type safety.
func (a *AccountAggregate) ApplyMoneyWithdrawnEvent(e *MoneyWithdrawnEvent, opts ...ApplyOption) error {
	return a.RaiseEvent(MoneyWithdrawnEventType, e)
}

// ApplyAccountClosedEvent applies an AccountClosedEvent with type safety.
func (a *AccountAggregate) ApplyAccountClosedEvent(e *AccountClosedEvent, opts ...ApplyOption) error {
	return a.RaiseEvent(AccountClosedEventType, e)
}

// AccountRepository provides type-safe repository operations for Account aggregates.
type AccountRepository struct {
	store         eventsourcing.EventStore
	snapshotStore eventsourcing.SnapshotStore
	applier       AccountEventApplier
}

// NewAccountRepository creates a new AccountRepository.
func NewAccountRepository(store eventsourcing.EventStore, snapshotStore eventsourcing.SnapshotStore, applier AccountEventApplier) *AccountRepository {
	return &AccountRepository{
		store:         store,
		snapshotStore: snapshotStore,
		applier:       applier,
	}
}

// Load loads an Account aggregate by ID.
func (r *AccountRepository) Load(id string) (*AccountAggregate, error) {
	agg := NewAccount(id, r.applier)

	// Try to load snapshot first
	if r.snapshotStore != nil {
		snapshot, err := r.snapshotStore.GetLatestSnapshot(id)
		if err == nil && snapshot != nil {
			acc := &Account{}
			if err := proto.Unmarshal(snapshot.Data, acc); err == nil {
				agg.Account = acc
				agg.version = snapshot.Version
			}
		}
	}

	// Load events after snapshot version
	events, err := r.store.LoadEvents(id, agg.version)
	if err != nil {
		return nil, err
	}

	// Apply events
	for _, event := range events {
		if err := agg.Apply(event); err != nil {
			return nil, err
		}
		agg.version = event.Version
	}

	return agg, nil
}

// Save saves an Account aggregate.
func (r *AccountRepository) Save(agg *AccountAggregate) error {
	events := agg.Events()
	if len(events) == 0 {
		return nil
	}

	if err := r.store.AppendEvents(agg.AggregateID(), agg.Version()-int64(len(events)), events); err != nil {
		return err
	}

	agg.ClearEvents()
	return nil
}

// RetryOnConflict retries an operation on optimistic concurrency conflicts.
func (r *AccountRepository) RetryOnConflict(id string, maxRetries int, fn func(*AccountAggregate) error) error {
	for i := 0; i <= maxRetries; i++ {
		agg, err := r.Load(id)
		if err != nil {
			return err
		}

		err = fn(agg)
		if err == nil {
			return nil
		}

		// Check if it's a concurrency error (would need proper error type check)
		if i == maxRetries {
			return err
		}
	}
	return nil
}

// Note: CqrsAccountCommandServiceHandler and CqrsAccountQueryServiceHandler
// are defined in account_server.cqrs.pb.go (generated by protoc-gen-cqrs)

// Event type constants
const (
	AccountOpenedEventType   = "account.v1.AccountOpenedEvent"
	MoneyDepositedEventType  = "account.v1.MoneyDepositedEvent"
	MoneyWithdrawnEventType  = "account.v1.MoneyWithdrawnEvent"
	AccountClosedEventType   = "account.v1.AccountClosedEvent"
	AccountOpenedEventV1Type = "account.v1.AccountOpenedEventV1"
)

// AccountOpenedEventHandler is a typed handler for AccountOpenedEvent
type AccountOpenedEventHandler func(ctx context.Context, event *AccountOpenedEvent, envelope *eventsourcing.EventEnvelope) error

// OnAccountOpened creates a typed event handler for AccountOpenedEvent
func OnAccountOpened(handler AccountOpenedEventHandler) eventsourcing.EventHandlerRegistration {
	return eventsourcing.EventHandlerRegistration{
		EventType: AccountOpenedEventType,
		Handler: func(ctx context.Context, envelope *eventsourcing.EventEnvelope) error {
			event := &AccountOpenedEvent{}
			if err := proto.Unmarshal(envelope.Data, event); err != nil {
				return err
			}
			return handler(ctx, event, envelope)
		},
	}
}

// MoneyDepositedEventHandler is a typed handler for MoneyDepositedEvent
type MoneyDepositedEventHandler func(ctx context.Context, event *MoneyDepositedEvent, envelope *eventsourcing.EventEnvelope) error

// OnMoneyDeposited creates a typed event handler for MoneyDepositedEvent
func OnMoneyDeposited(handler MoneyDepositedEventHandler) eventsourcing.EventHandlerRegistration {
	return eventsourcing.EventHandlerRegistration{
		EventType: MoneyDepositedEventType,
		Handler: func(ctx context.Context, envelope *eventsourcing.EventEnvelope) error {
			event := &MoneyDepositedEvent{}
			if err := proto.Unmarshal(envelope.Data, event); err != nil {
				return err
			}
			return handler(ctx, event, envelope)
		},
	}
}

// MoneyWithdrawnEventHandler is a typed handler for MoneyWithdrawnEvent
type MoneyWithdrawnEventHandler func(ctx context.Context, event *MoneyWithdrawnEvent, envelope *eventsourcing.EventEnvelope) error

// OnMoneyWithdrawn creates a typed event handler for MoneyWithdrawnEvent
func OnMoneyWithdrawn(handler MoneyWithdrawnEventHandler) eventsourcing.EventHandlerRegistration {
	return eventsourcing.EventHandlerRegistration{
		EventType: MoneyWithdrawnEventType,
		Handler: func(ctx context.Context, envelope *eventsourcing.EventEnvelope) error {
			event := &MoneyWithdrawnEvent{}
			if err := proto.Unmarshal(envelope.Data, event); err != nil {
				return err
			}
			return handler(ctx, event, envelope)
		},
	}
}

// AccountClosedEventHandler is a typed handler for AccountClosedEvent
type AccountClosedEventHandler func(ctx context.Context, event *AccountClosedEvent, envelope *eventsourcing.EventEnvelope) error

// OnAccountClosed creates a typed event handler for AccountClosedEvent
func OnAccountClosed(handler AccountClosedEventHandler) eventsourcing.EventHandlerRegistration {
	return eventsourcing.EventHandlerRegistration{
		EventType: AccountClosedEventType,
		Handler: func(ctx context.Context, envelope *eventsourcing.EventEnvelope) error {
			event := &AccountClosedEvent{}
			if err := proto.Unmarshal(envelope.Data, event); err != nil {
				return err
			}
			return handler(ctx, event, envelope)
		},
	}
}
