// Code generated by protoc-gen-eventsourcing. DO NOT EDIT.
// version: 0.0.15
// Aggregate handler interfaces for v1

package accountv1

import (
	"context"

	"github.com/plaenen/eventstore/pkg/eventsourcing"
)

// AccountHandler defines methods for Account aggregate operations
// Each method receives the request and functional options for context like authentication, tracing, etc.
type AccountHandler interface {
	// OpenAccount handles the OpenAccount operation
	OpenAccount(ctx context.Context, req *OpenAccountCommand, opts ...eventsourcing.MethodOption) (*OpenAccountResponse, error)
	// Deposit handles the Deposit operation
	Deposit(ctx context.Context, req *DepositCommand, opts ...eventsourcing.MethodOption) (*DepositResponse, error)
	// Withdraw handles the Withdraw operation
	Withdraw(ctx context.Context, req *WithdrawCommand, opts ...eventsourcing.MethodOption) (*WithdrawResponse, error)
	// CloseAccount handles the CloseAccount operation
	CloseAccount(ctx context.Context, req *CloseAccountCommand, opts ...eventsourcing.MethodOption) (*CloseAccountResponse, error)
	// GetAccount handles the GetAccount operation
	GetAccount(ctx context.Context, req *GetAccountRequest, opts ...eventsourcing.MethodOption) (*AccountView, error)
	// ListAccounts handles the ListAccounts operation
	ListAccounts(ctx context.Context, req *ListAccountsRequest, opts ...eventsourcing.MethodOption) (*ListAccountsResponse, error)
	// GetAccountBalance handles the GetAccountBalance operation
	GetAccountBalance(ctx context.Context, req *GetAccountBalanceRequest, opts ...eventsourcing.MethodOption) (*BalanceView, error)
	// GetAccountHistory handles the GetAccountHistory operation
	GetAccountHistory(ctx context.Context, req *GetAccountHistoryRequest, opts ...eventsourcing.MethodOption) (*AccountHistoryResponse, error)
}

// UnimplementedAccountHandler provides default implementations returning 'not implemented' errors
// Embed this in your implementation to only implement the methods you need:
//
//	type MyHandler struct {
//	    UnimplementedAccountHandler
//	    // your fields...
//	}
//
//	func (h *MyHandler) OpenAccount(ctx context.Context, req *OpenAccountCommand, opts ...eventsourcing.MethodOption) (*OpenAccountResponse, error) {
//	    // Your implementation
//	}
type UnimplementedAccountHandler struct{}

// OpenAccount returns a 'not implemented' error
func (h *UnimplementedAccountHandler) OpenAccount(ctx context.Context, req *OpenAccountCommand, opts ...eventsourcing.MethodOption) (*OpenAccountResponse, error) {
	return nil, &eventsourcing.NotImplementedError{Method: "OpenAccount"}
}

// Deposit returns a 'not implemented' error
func (h *UnimplementedAccountHandler) Deposit(ctx context.Context, req *DepositCommand, opts ...eventsourcing.MethodOption) (*DepositResponse, error) {
	return nil, &eventsourcing.NotImplementedError{Method: "Deposit"}
}

// Withdraw returns a 'not implemented' error
func (h *UnimplementedAccountHandler) Withdraw(ctx context.Context, req *WithdrawCommand, opts ...eventsourcing.MethodOption) (*WithdrawResponse, error) {
	return nil, &eventsourcing.NotImplementedError{Method: "Withdraw"}
}

// CloseAccount returns a 'not implemented' error
func (h *UnimplementedAccountHandler) CloseAccount(ctx context.Context, req *CloseAccountCommand, opts ...eventsourcing.MethodOption) (*CloseAccountResponse, error) {
	return nil, &eventsourcing.NotImplementedError{Method: "CloseAccount"}
}

// GetAccount returns a 'not implemented' error
func (h *UnimplementedAccountHandler) GetAccount(ctx context.Context, req *GetAccountRequest, opts ...eventsourcing.MethodOption) (*AccountView, error) {
	return nil, &eventsourcing.NotImplementedError{Method: "GetAccount"}
}

// ListAccounts returns a 'not implemented' error
func (h *UnimplementedAccountHandler) ListAccounts(ctx context.Context, req *ListAccountsRequest, opts ...eventsourcing.MethodOption) (*ListAccountsResponse, error) {
	return nil, &eventsourcing.NotImplementedError{Method: "ListAccounts"}
}

// GetAccountBalance returns a 'not implemented' error
func (h *UnimplementedAccountHandler) GetAccountBalance(ctx context.Context, req *GetAccountBalanceRequest, opts ...eventsourcing.MethodOption) (*BalanceView, error) {
	return nil, &eventsourcing.NotImplementedError{Method: "GetAccountBalance"}
}

// GetAccountHistory returns a 'not implemented' error
func (h *UnimplementedAccountHandler) GetAccountHistory(ctx context.Context, req *GetAccountHistoryRequest, opts ...eventsourcing.MethodOption) (*AccountHistoryResponse, error) {
	return nil, &eventsourcing.NotImplementedError{Method: "GetAccountHistory"}
}
