// Code generated by protoc-gen-eventsourcing. DO NOT EDIT.
// version: 0.0.20
// Server service for v1

package accountv1

import (
	"context"
	"fmt"

	"github.com/plaenen/eventstore/pkg/eventsourcing"
	"google.golang.org/protobuf/proto"
)

// AccountCommandServiceServer routes requests to the AccountHandler implementation
type AccountCommandServiceServer struct {
	server  eventsourcing.Server
	handler AccountHandler
}

// NewAccountCommandServiceServer creates a new server
func NewAccountCommandServiceServer(server eventsourcing.Server, handler AccountHandler) *AccountCommandServiceServer {
	return &AccountCommandServiceServer{
		server:  server,
		handler: handler,
	}
}

// Start registers handlers and starts the server
func (s *AccountCommandServiceServer) Start(ctx context.Context) error {
	if err := s.server.RegisterHandler("account.v1.AccountCommandService.OpenAccount", s.handleOpenAccount); err != nil {
		return fmt.Errorf("failed to register OpenAccount: %w", err)
	}
	if err := s.server.RegisterHandler("account.v1.AccountCommandService.Deposit", s.handleDeposit); err != nil {
		return fmt.Errorf("failed to register Deposit: %w", err)
	}
	if err := s.server.RegisterHandler("account.v1.AccountCommandService.Withdraw", s.handleWithdraw); err != nil {
		return fmt.Errorf("failed to register Withdraw: %w", err)
	}
	if err := s.server.RegisterHandler("account.v1.AccountCommandService.CloseAccount", s.handleCloseAccount); err != nil {
		return fmt.Errorf("failed to register CloseAccount: %w", err)
	}

	return s.server.Start(ctx)
}

func (s *AccountCommandServiceServer) handleOpenAccount(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*OpenAccountCommand)
	// Extract method options from context (set by middleware)
	opts := eventsourcing.ExtractMethodOptionsFromContext(ctx)
	result, err := s.handler.OpenAccount(ctx, req, opts...)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *AccountCommandServiceServer) handleDeposit(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*DepositCommand)
	// Extract method options from context (set by middleware)
	opts := eventsourcing.ExtractMethodOptionsFromContext(ctx)
	result, err := s.handler.Deposit(ctx, req, opts...)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *AccountCommandServiceServer) handleWithdraw(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*WithdrawCommand)
	// Extract method options from context (set by middleware)
	opts := eventsourcing.ExtractMethodOptionsFromContext(ctx)
	result, err := s.handler.Withdraw(ctx, req, opts...)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *AccountCommandServiceServer) handleCloseAccount(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*CloseAccountCommand)
	// Extract method options from context (set by middleware)
	opts := eventsourcing.ExtractMethodOptionsFromContext(ctx)
	result, err := s.handler.CloseAccount(ctx, req, opts...)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

// Close stops the server
func (s *AccountCommandServiceServer) Close() error {
	return s.server.Close()
}

// AccountQueryServiceServer routes requests to the AccountHandler implementation
type AccountQueryServiceServer struct {
	server  eventsourcing.Server
	handler AccountHandler
}

// NewAccountQueryServiceServer creates a new server
func NewAccountQueryServiceServer(server eventsourcing.Server, handler AccountHandler) *AccountQueryServiceServer {
	return &AccountQueryServiceServer{
		server:  server,
		handler: handler,
	}
}

// Start registers handlers and starts the server
func (s *AccountQueryServiceServer) Start(ctx context.Context) error {
	if err := s.server.RegisterHandler("account.v1.AccountQueryService.GetAccount", s.handleGetAccount); err != nil {
		return fmt.Errorf("failed to register GetAccount: %w", err)
	}
	if err := s.server.RegisterHandler("account.v1.AccountQueryService.ListAccounts", s.handleListAccounts); err != nil {
		return fmt.Errorf("failed to register ListAccounts: %w", err)
	}
	if err := s.server.RegisterHandler("account.v1.AccountQueryService.GetAccountBalance", s.handleGetAccountBalance); err != nil {
		return fmt.Errorf("failed to register GetAccountBalance: %w", err)
	}
	if err := s.server.RegisterHandler("account.v1.AccountQueryService.GetAccountHistory", s.handleGetAccountHistory); err != nil {
		return fmt.Errorf("failed to register GetAccountHistory: %w", err)
	}

	return s.server.Start(ctx)
}

func (s *AccountQueryServiceServer) handleGetAccount(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*GetAccountRequest)
	// Extract method options from context (set by middleware)
	opts := eventsourcing.ExtractMethodOptionsFromContext(ctx)
	result, err := s.handler.GetAccount(ctx, req, opts...)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *AccountQueryServiceServer) handleListAccounts(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*ListAccountsRequest)
	// Extract method options from context (set by middleware)
	opts := eventsourcing.ExtractMethodOptionsFromContext(ctx)
	result, err := s.handler.ListAccounts(ctx, req, opts...)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *AccountQueryServiceServer) handleGetAccountBalance(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*GetAccountBalanceRequest)
	// Extract method options from context (set by middleware)
	opts := eventsourcing.ExtractMethodOptionsFromContext(ctx)
	result, err := s.handler.GetAccountBalance(ctx, req, opts...)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *AccountQueryServiceServer) handleGetAccountHistory(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*GetAccountHistoryRequest)
	// Extract method options from context (set by middleware)
	opts := eventsourcing.ExtractMethodOptionsFromContext(ctx)
	result, err := s.handler.GetAccountHistory(ctx, req, opts...)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

// Close stops the server
func (s *AccountQueryServiceServer) Close() error {
	return s.server.Close()
}
