// Code generated by protoc-gen-cqrs. DO NOT EDIT.
// version: 0.0.1
// CQRS Clients for v1

package accountv1

import (
	"context"

	"github.com/plaenen/eventstore/pkg/cqrs"
)

// AccountCommandServiceClient provides type-safe client methods for AccountCommandService
type AccountCommandServiceClient struct {
	transport cqrs.Transport
}

// NewAccountCommandServiceClient creates a new client for AccountCommandService
func NewAccountCommandServiceClient(transport cqrs.Transport) *AccountCommandServiceClient {
	return &AccountCommandServiceClient{transport: transport}
}

// OpenAccount sends a OpenAccount command and returns the response
func (c *AccountCommandServiceClient) OpenAccount(ctx context.Context, cmd *OpenAccountCommand) (*OpenAccountResponse, error) {
	// Send request via transport
	resp, err := c.transport.Request(ctx, "account.v1.AccountCommandService.OpenAccount", cmd)
	if err != nil {
		return nil, err
	}

	// Check if request succeeded
	if !resp.Success {
		return nil, resp.AsError()
	}

	// Unpack response data
	result := &OpenAccountResponse{}
	if err := resp.UnpackData(result); err != nil {
		return nil, err
	}

	return result, nil
}

// Deposit sends a Deposit command and returns the response
func (c *AccountCommandServiceClient) Deposit(ctx context.Context, cmd *DepositCommand) (*DepositResponse, error) {
	// Send request via transport
	resp, err := c.transport.Request(ctx, "account.v1.AccountCommandService.Deposit", cmd)
	if err != nil {
		return nil, err
	}

	// Check if request succeeded
	if !resp.Success {
		return nil, resp.AsError()
	}

	// Unpack response data
	result := &DepositResponse{}
	if err := resp.UnpackData(result); err != nil {
		return nil, err
	}

	return result, nil
}

// Withdraw sends a Withdraw command and returns the response
func (c *AccountCommandServiceClient) Withdraw(ctx context.Context, cmd *WithdrawCommand) (*WithdrawResponse, error) {
	// Send request via transport
	resp, err := c.transport.Request(ctx, "account.v1.AccountCommandService.Withdraw", cmd)
	if err != nil {
		return nil, err
	}

	// Check if request succeeded
	if !resp.Success {
		return nil, resp.AsError()
	}

	// Unpack response data
	result := &WithdrawResponse{}
	if err := resp.UnpackData(result); err != nil {
		return nil, err
	}

	return result, nil
}

// CloseAccount sends a CloseAccount command and returns the response
func (c *AccountCommandServiceClient) CloseAccount(ctx context.Context, cmd *CloseAccountCommand) (*CloseAccountResponse, error) {
	// Send request via transport
	resp, err := c.transport.Request(ctx, "account.v1.AccountCommandService.CloseAccount", cmd)
	if err != nil {
		return nil, err
	}

	// Check if request succeeded
	if !resp.Success {
		return nil, resp.AsError()
	}

	// Unpack response data
	result := &CloseAccountResponse{}
	if err := resp.UnpackData(result); err != nil {
		return nil, err
	}

	return result, nil
}

// AccountQueryServiceClient provides type-safe client methods for AccountQueryService
type AccountQueryServiceClient struct {
	transport cqrs.Transport
}

// NewAccountQueryServiceClient creates a new client for AccountQueryService
func NewAccountQueryServiceClient(transport cqrs.Transport) *AccountQueryServiceClient {
	return &AccountQueryServiceClient{transport: transport}
}

// GetAccount executes a GetAccount query and returns the result
func (c *AccountQueryServiceClient) GetAccount(ctx context.Context, query *GetAccountRequest) (*AccountView, error) {
	// Send request via transport
	resp, err := c.transport.Request(ctx, "account.v1.AccountQueryService.GetAccount", query)
	if err != nil {
		return nil, err
	}

	// Check if request succeeded
	if !resp.Success {
		return nil, resp.AsError()
	}

	// Unpack response data
	result := &AccountView{}
	if err := resp.UnpackData(result); err != nil {
		return nil, err
	}

	return result, nil
}

// ListAccounts executes a ListAccounts query and returns the result
func (c *AccountQueryServiceClient) ListAccounts(ctx context.Context, query *ListAccountsRequest) (*ListAccountsResponse, error) {
	// Send request via transport
	resp, err := c.transport.Request(ctx, "account.v1.AccountQueryService.ListAccounts", query)
	if err != nil {
		return nil, err
	}

	// Check if request succeeded
	if !resp.Success {
		return nil, resp.AsError()
	}

	// Unpack response data
	result := &ListAccountsResponse{}
	if err := resp.UnpackData(result); err != nil {
		return nil, err
	}

	return result, nil
}

// GetAccountBalance executes a GetAccountBalance query and returns the result
func (c *AccountQueryServiceClient) GetAccountBalance(ctx context.Context, query *GetAccountBalanceRequest) (*BalanceView, error) {
	// Send request via transport
	resp, err := c.transport.Request(ctx, "account.v1.AccountQueryService.GetAccountBalance", query)
	if err != nil {
		return nil, err
	}

	// Check if request succeeded
	if !resp.Success {
		return nil, resp.AsError()
	}

	// Unpack response data
	result := &BalanceView{}
	if err := resp.UnpackData(result); err != nil {
		return nil, err
	}

	return result, nil
}

// GetAccountHistory executes a GetAccountHistory query and returns the result
func (c *AccountQueryServiceClient) GetAccountHistory(ctx context.Context, query *GetAccountHistoryRequest) (*AccountHistoryResponse, error) {
	// Send request via transport
	resp, err := c.transport.Request(ctx, "account.v1.AccountQueryService.GetAccountHistory", query)
	if err != nil {
		return nil, err
	}

	// Check if request succeeded
	if !resp.Success {
		return nil, resp.AsError()
	}

	// Unpack response data
	result := &AccountHistoryResponse{}
	if err := resp.UnpackData(result); err != nil {
		return nil, err
	}

	return result, nil
}
