// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: lead/v1/aggregate_fixed.proto

package leadv1

import (
	_ "github.com/plaenen/eventstore/pkg/eventsourcing"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeadFixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadFixed) Reset() {
	*x = LeadFixed{}
	mi := &file_lead_v1_aggregate_fixed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadFixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadFixed) ProtoMessage() {}

func (x *LeadFixed) ProtoReflect() protoreflect.Message {
	mi := &file_lead_v1_aggregate_fixed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadFixed.ProtoReflect.Descriptor instead.
func (*LeadFixed) Descriptor() ([]byte, []int) {
	return file_lead_v1_aggregate_fixed_proto_rawDescGZIP(), []int{0}
}

func (x *LeadFixed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LeadCapturedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadCapturedEvent) Reset() {
	*x = LeadCapturedEvent{}
	mi := &file_lead_v1_aggregate_fixed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadCapturedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadCapturedEvent) ProtoMessage() {}

func (x *LeadCapturedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lead_v1_aggregate_fixed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadCapturedEvent.ProtoReflect.Descriptor instead.
func (*LeadCapturedEvent) Descriptor() ([]byte, []int) {
	return file_lead_v1_aggregate_fixed_proto_rawDescGZIP(), []int{1}
}

func (x *LeadCapturedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_lead_v1_aggregate_fixed_proto protoreflect.FileDescriptor

const file_lead_v1_aggregate_fixed_proto_rawDesc = "" +
	"\n" +
	"\x1dlead/v1/aggregate_fixed.proto\x12\alead.v1\x1a\x1beventsourcing/options.proto\"%\n" +
	"\tLeadFixed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id:\b\x9a\xb5\x18\x04\n" +
	"\x02id\"4\n" +
	"\x11LeadCapturedEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id:\x0f\xa2\xb5\x18\v\n" +
	"\tLeadFixedB7Z5github.com/plaenen/eventstore/repro/pb/lead/v1;leadv1b\x06proto3"

var (
	file_lead_v1_aggregate_fixed_proto_rawDescOnce sync.Once
	file_lead_v1_aggregate_fixed_proto_rawDescData []byte
)

func file_lead_v1_aggregate_fixed_proto_rawDescGZIP() []byte {
	file_lead_v1_aggregate_fixed_proto_rawDescOnce.Do(func() {
		file_lead_v1_aggregate_fixed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lead_v1_aggregate_fixed_proto_rawDesc), len(file_lead_v1_aggregate_fixed_proto_rawDesc)))
	})
	return file_lead_v1_aggregate_fixed_proto_rawDescData
}

var file_lead_v1_aggregate_fixed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lead_v1_aggregate_fixed_proto_goTypes = []any{
	(*LeadFixed)(nil),         // 0: lead.v1.LeadFixed
	(*LeadCapturedEvent)(nil), // 1: lead.v1.LeadCapturedEvent
}
var file_lead_v1_aggregate_fixed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lead_v1_aggregate_fixed_proto_init() }
func file_lead_v1_aggregate_fixed_proto_init() {
	if File_lead_v1_aggregate_fixed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lead_v1_aggregate_fixed_proto_rawDesc), len(file_lead_v1_aggregate_fixed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lead_v1_aggregate_fixed_proto_goTypes,
		DependencyIndexes: file_lead_v1_aggregate_fixed_proto_depIdxs,
		MessageInfos:      file_lead_v1_aggregate_fixed_proto_msgTypes,
	}.Build()
	File_lead_v1_aggregate_fixed_proto = out.File
	file_lead_v1_aggregate_fixed_proto_goTypes = nil
	file_lead_v1_aggregate_fixed_proto_depIdxs = nil
}
