// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orders/v1/orders.proto

package ordersv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/plaenen/eventstore/examples/pb/orders/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrderCommandServiceName is the fully-qualified name of the OrderCommandService service.
	OrderCommandServiceName = "orders.v1.OrderCommandService"
	// OrderQueryServiceName is the fully-qualified name of the OrderQueryService service.
	OrderQueryServiceName = "orders.v1.OrderQueryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrderCommandServiceCreateOrderProcedure is the fully-qualified name of the OrderCommandService's
	// CreateOrder RPC.
	OrderCommandServiceCreateOrderProcedure = "/orders.v1.OrderCommandService/CreateOrder"
	// OrderCommandServiceCancelOrderProcedure is the fully-qualified name of the OrderCommandService's
	// CancelOrder RPC.
	OrderCommandServiceCancelOrderProcedure = "/orders.v1.OrderCommandService/CancelOrder"
	// OrderCommandServiceUpdateOrderStatusProcedure is the fully-qualified name of the
	// OrderCommandService's UpdateOrderStatus RPC.
	OrderCommandServiceUpdateOrderStatusProcedure = "/orders.v1.OrderCommandService/UpdateOrderStatus"
	// OrderQueryServiceGetOrderProcedure is the fully-qualified name of the OrderQueryService's
	// GetOrder RPC.
	OrderQueryServiceGetOrderProcedure = "/orders.v1.OrderQueryService/GetOrder"
	// OrderQueryServiceListOrdersProcedure is the fully-qualified name of the OrderQueryService's
	// ListOrders RPC.
	OrderQueryServiceListOrdersProcedure = "/orders.v1.OrderQueryService/ListOrders"
	// OrderQueryServiceGetOrdersByStatusProcedure is the fully-qualified name of the
	// OrderQueryService's GetOrdersByStatus RPC.
	OrderQueryServiceGetOrdersByStatusProcedure = "/orders.v1.OrderQueryService/GetOrdersByStatus"
)

// OrderCommandServiceClient is a client for the orders.v1.OrderCommandService service.
type OrderCommandServiceClient interface {
	CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error)
	CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error)
	UpdateOrderStatus(context.Context, *connect.Request[v1.UpdateOrderStatusRequest]) (*connect.Response[v1.UpdateOrderStatusResponse], error)
}

// NewOrderCommandServiceClient constructs a client for the orders.v1.OrderCommandService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrderCommandServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrderCommandServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	orderCommandServiceMethods := v1.File_orders_v1_orders_proto.Services().ByName("OrderCommandService").Methods()
	return &orderCommandServiceClient{
		createOrder: connect.NewClient[v1.CreateOrderRequest, v1.CreateOrderResponse](
			httpClient,
			baseURL+OrderCommandServiceCreateOrderProcedure,
			connect.WithSchema(orderCommandServiceMethods.ByName("CreateOrder")),
			connect.WithClientOptions(opts...),
		),
		cancelOrder: connect.NewClient[v1.CancelOrderRequest, v1.CancelOrderResponse](
			httpClient,
			baseURL+OrderCommandServiceCancelOrderProcedure,
			connect.WithSchema(orderCommandServiceMethods.ByName("CancelOrder")),
			connect.WithClientOptions(opts...),
		),
		updateOrderStatus: connect.NewClient[v1.UpdateOrderStatusRequest, v1.UpdateOrderStatusResponse](
			httpClient,
			baseURL+OrderCommandServiceUpdateOrderStatusProcedure,
			connect.WithSchema(orderCommandServiceMethods.ByName("UpdateOrderStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// orderCommandServiceClient implements OrderCommandServiceClient.
type orderCommandServiceClient struct {
	createOrder       *connect.Client[v1.CreateOrderRequest, v1.CreateOrderResponse]
	cancelOrder       *connect.Client[v1.CancelOrderRequest, v1.CancelOrderResponse]
	updateOrderStatus *connect.Client[v1.UpdateOrderStatusRequest, v1.UpdateOrderStatusResponse]
}

// CreateOrder calls orders.v1.OrderCommandService.CreateOrder.
func (c *orderCommandServiceClient) CreateOrder(ctx context.Context, req *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error) {
	return c.createOrder.CallUnary(ctx, req)
}

// CancelOrder calls orders.v1.OrderCommandService.CancelOrder.
func (c *orderCommandServiceClient) CancelOrder(ctx context.Context, req *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error) {
	return c.cancelOrder.CallUnary(ctx, req)
}

// UpdateOrderStatus calls orders.v1.OrderCommandService.UpdateOrderStatus.
func (c *orderCommandServiceClient) UpdateOrderStatus(ctx context.Context, req *connect.Request[v1.UpdateOrderStatusRequest]) (*connect.Response[v1.UpdateOrderStatusResponse], error) {
	return c.updateOrderStatus.CallUnary(ctx, req)
}

// OrderCommandServiceHandler is an implementation of the orders.v1.OrderCommandService service.
type OrderCommandServiceHandler interface {
	CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error)
	CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error)
	UpdateOrderStatus(context.Context, *connect.Request[v1.UpdateOrderStatusRequest]) (*connect.Response[v1.UpdateOrderStatusResponse], error)
}

// NewOrderCommandServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrderCommandServiceHandler(svc OrderCommandServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	orderCommandServiceMethods := v1.File_orders_v1_orders_proto.Services().ByName("OrderCommandService").Methods()
	orderCommandServiceCreateOrderHandler := connect.NewUnaryHandler(
		OrderCommandServiceCreateOrderProcedure,
		svc.CreateOrder,
		connect.WithSchema(orderCommandServiceMethods.ByName("CreateOrder")),
		connect.WithHandlerOptions(opts...),
	)
	orderCommandServiceCancelOrderHandler := connect.NewUnaryHandler(
		OrderCommandServiceCancelOrderProcedure,
		svc.CancelOrder,
		connect.WithSchema(orderCommandServiceMethods.ByName("CancelOrder")),
		connect.WithHandlerOptions(opts...),
	)
	orderCommandServiceUpdateOrderStatusHandler := connect.NewUnaryHandler(
		OrderCommandServiceUpdateOrderStatusProcedure,
		svc.UpdateOrderStatus,
		connect.WithSchema(orderCommandServiceMethods.ByName("UpdateOrderStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orders.v1.OrderCommandService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrderCommandServiceCreateOrderProcedure:
			orderCommandServiceCreateOrderHandler.ServeHTTP(w, r)
		case OrderCommandServiceCancelOrderProcedure:
			orderCommandServiceCancelOrderHandler.ServeHTTP(w, r)
		case OrderCommandServiceUpdateOrderStatusProcedure:
			orderCommandServiceUpdateOrderStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrderCommandServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrderCommandServiceHandler struct{}

func (UnimplementedOrderCommandServiceHandler) CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orders.v1.OrderCommandService.CreateOrder is not implemented"))
}

func (UnimplementedOrderCommandServiceHandler) CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orders.v1.OrderCommandService.CancelOrder is not implemented"))
}

func (UnimplementedOrderCommandServiceHandler) UpdateOrderStatus(context.Context, *connect.Request[v1.UpdateOrderStatusRequest]) (*connect.Response[v1.UpdateOrderStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orders.v1.OrderCommandService.UpdateOrderStatus is not implemented"))
}

// OrderQueryServiceClient is a client for the orders.v1.OrderQueryService service.
type OrderQueryServiceClient interface {
	GetOrder(context.Context, *connect.Request[v1.GetOrderRequest]) (*connect.Response[v1.Order], error)
	ListOrders(context.Context, *connect.Request[v1.ListOrdersRequest]) (*connect.Response[v1.ListOrdersResponse], error)
	GetOrdersByStatus(context.Context, *connect.Request[v1.GetOrdersByStatusRequest]) (*connect.Response[v1.ListOrdersResponse], error)
}

// NewOrderQueryServiceClient constructs a client for the orders.v1.OrderQueryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrderQueryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrderQueryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	orderQueryServiceMethods := v1.File_orders_v1_orders_proto.Services().ByName("OrderQueryService").Methods()
	return &orderQueryServiceClient{
		getOrder: connect.NewClient[v1.GetOrderRequest, v1.Order](
			httpClient,
			baseURL+OrderQueryServiceGetOrderProcedure,
			connect.WithSchema(orderQueryServiceMethods.ByName("GetOrder")),
			connect.WithClientOptions(opts...),
		),
		listOrders: connect.NewClient[v1.ListOrdersRequest, v1.ListOrdersResponse](
			httpClient,
			baseURL+OrderQueryServiceListOrdersProcedure,
			connect.WithSchema(orderQueryServiceMethods.ByName("ListOrders")),
			connect.WithClientOptions(opts...),
		),
		getOrdersByStatus: connect.NewClient[v1.GetOrdersByStatusRequest, v1.ListOrdersResponse](
			httpClient,
			baseURL+OrderQueryServiceGetOrdersByStatusProcedure,
			connect.WithSchema(orderQueryServiceMethods.ByName("GetOrdersByStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// orderQueryServiceClient implements OrderQueryServiceClient.
type orderQueryServiceClient struct {
	getOrder          *connect.Client[v1.GetOrderRequest, v1.Order]
	listOrders        *connect.Client[v1.ListOrdersRequest, v1.ListOrdersResponse]
	getOrdersByStatus *connect.Client[v1.GetOrdersByStatusRequest, v1.ListOrdersResponse]
}

// GetOrder calls orders.v1.OrderQueryService.GetOrder.
func (c *orderQueryServiceClient) GetOrder(ctx context.Context, req *connect.Request[v1.GetOrderRequest]) (*connect.Response[v1.Order], error) {
	return c.getOrder.CallUnary(ctx, req)
}

// ListOrders calls orders.v1.OrderQueryService.ListOrders.
func (c *orderQueryServiceClient) ListOrders(ctx context.Context, req *connect.Request[v1.ListOrdersRequest]) (*connect.Response[v1.ListOrdersResponse], error) {
	return c.listOrders.CallUnary(ctx, req)
}

// GetOrdersByStatus calls orders.v1.OrderQueryService.GetOrdersByStatus.
func (c *orderQueryServiceClient) GetOrdersByStatus(ctx context.Context, req *connect.Request[v1.GetOrdersByStatusRequest]) (*connect.Response[v1.ListOrdersResponse], error) {
	return c.getOrdersByStatus.CallUnary(ctx, req)
}

// OrderQueryServiceHandler is an implementation of the orders.v1.OrderQueryService service.
type OrderQueryServiceHandler interface {
	GetOrder(context.Context, *connect.Request[v1.GetOrderRequest]) (*connect.Response[v1.Order], error)
	ListOrders(context.Context, *connect.Request[v1.ListOrdersRequest]) (*connect.Response[v1.ListOrdersResponse], error)
	GetOrdersByStatus(context.Context, *connect.Request[v1.GetOrdersByStatusRequest]) (*connect.Response[v1.ListOrdersResponse], error)
}

// NewOrderQueryServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrderQueryServiceHandler(svc OrderQueryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	orderQueryServiceMethods := v1.File_orders_v1_orders_proto.Services().ByName("OrderQueryService").Methods()
	orderQueryServiceGetOrderHandler := connect.NewUnaryHandler(
		OrderQueryServiceGetOrderProcedure,
		svc.GetOrder,
		connect.WithSchema(orderQueryServiceMethods.ByName("GetOrder")),
		connect.WithHandlerOptions(opts...),
	)
	orderQueryServiceListOrdersHandler := connect.NewUnaryHandler(
		OrderQueryServiceListOrdersProcedure,
		svc.ListOrders,
		connect.WithSchema(orderQueryServiceMethods.ByName("ListOrders")),
		connect.WithHandlerOptions(opts...),
	)
	orderQueryServiceGetOrdersByStatusHandler := connect.NewUnaryHandler(
		OrderQueryServiceGetOrdersByStatusProcedure,
		svc.GetOrdersByStatus,
		connect.WithSchema(orderQueryServiceMethods.ByName("GetOrdersByStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orders.v1.OrderQueryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrderQueryServiceGetOrderProcedure:
			orderQueryServiceGetOrderHandler.ServeHTTP(w, r)
		case OrderQueryServiceListOrdersProcedure:
			orderQueryServiceListOrdersHandler.ServeHTTP(w, r)
		case OrderQueryServiceGetOrdersByStatusProcedure:
			orderQueryServiceGetOrdersByStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrderQueryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrderQueryServiceHandler struct{}

func (UnimplementedOrderQueryServiceHandler) GetOrder(context.Context, *connect.Request[v1.GetOrderRequest]) (*connect.Response[v1.Order], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orders.v1.OrderQueryService.GetOrder is not implemented"))
}

func (UnimplementedOrderQueryServiceHandler) ListOrders(context.Context, *connect.Request[v1.ListOrdersRequest]) (*connect.Response[v1.ListOrdersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orders.v1.OrderQueryService.ListOrders is not implemented"))
}

func (UnimplementedOrderQueryServiceHandler) GetOrdersByStatus(context.Context, *connect.Request[v1.GetOrdersByStatusRequest]) (*connect.Response[v1.ListOrdersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orders.v1.OrderQueryService.GetOrdersByStatus is not implemented"))
}
