// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: entity/v1/entity.proto

package entityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_DISABLED    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_DISABLED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_DISABLED":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_entity_v1_entity_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_entity_v1_entity_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_entity_v1_entity_proto_rawDescGZIP(), []int{0}
}

var File_entity_v1_entity_proto protoreflect.FileDescriptor

const file_entity_v1_entity_proto_rawDesc = "" +
	"\n" +
	"\x16entity/v1/entity.proto\x12\tentity.v1*H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_DISABLED\x10\x02B\x9c\x01\n" +
	"\rcom.entity.v1B\vEntityProtoP\x01Z9github.com/plaenen/eventstore/examples/entity/v1;entityv1\xa2\x02\x03EXX\xaa\x02\tEntity.V1\xca\x02\tEntity\\V1\xe2\x02\x15Entity\\V1\\GPBMetadata\xea\x02\n" +
	"Entity::V1b\x06proto3"

var (
	file_entity_v1_entity_proto_rawDescOnce sync.Once
	file_entity_v1_entity_proto_rawDescData []byte
)

func file_entity_v1_entity_proto_rawDescGZIP() []byte {
	file_entity_v1_entity_proto_rawDescOnce.Do(func() {
		file_entity_v1_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_v1_entity_proto_rawDesc), len(file_entity_v1_entity_proto_rawDesc)))
	})
	return file_entity_v1_entity_proto_rawDescData
}

var file_entity_v1_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entity_v1_entity_proto_goTypes = []any{
	(Status)(0), // 0: entity.v1.Status
}
var file_entity_v1_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_v1_entity_proto_init() }
func file_entity_v1_entity_proto_init() {
	if File_entity_v1_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_v1_entity_proto_rawDesc), len(file_entity_v1_entity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_v1_entity_proto_goTypes,
		DependencyIndexes: file_entity_v1_entity_proto_depIdxs,
		EnumInfos:         file_entity_v1_entity_proto_enumTypes,
	}.Build()
	File_entity_v1_entity_proto = out.File
	file_entity_v1_entity_proto_goTypes = nil
	file_entity_v1_entity_proto_depIdxs = nil
}
