// Code generated by protoc-gen-cqrs. DO NOT EDIT.
// version: 0.0.1
// Server service for v1

package ordersv1

import (
	"context"
	"fmt"

	"github.com/plaenen/eventstore/pkg/cqrs"
	"github.com/plaenen/eventstore/pkg/eventsourcing"
	"google.golang.org/protobuf/proto"
)

// CqrsOrderCommandServiceHandler defines the business logic for OrderCommandService
type CqrsOrderCommandServiceHandler interface {
	CreateOrder(ctx context.Context, cmd *CreateOrderRequest) (*CreateOrderResponse, error)
	CancelOrder(ctx context.Context, cmd *CancelOrderRequest) (*CancelOrderResponse, error)
	UpdateOrderStatus(ctx context.Context, cmd *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error)
}

// CqrsOrderCommandServiceServer routes requests to the CqrsOrderCommandServiceHandler implementation
type CqrsOrderCommandServiceServer struct {
	server  cqrs.Server
	handler CqrsOrderCommandServiceHandler
}

// NewCqrsOrderCommandServiceServer creates a new server
func NewCqrsOrderCommandServiceServer(server cqrs.Server, handler CqrsOrderCommandServiceHandler) *CqrsOrderCommandServiceServer {
	return &CqrsOrderCommandServiceServer{
		server:  server,
		handler: handler,
	}
}

// Start registers handlers and starts the server
func (s *CqrsOrderCommandServiceServer) Start(ctx context.Context) error {
	if err := s.server.RegisterHandler("orders.v1.OrderCommandService.CreateOrder", s.handleCreateOrder); err != nil {
		return fmt.Errorf("failed to register CreateOrder: %w", err)
	}
	if err := s.server.RegisterHandler("orders.v1.OrderCommandService.CancelOrder", s.handleCancelOrder); err != nil {
		return fmt.Errorf("failed to register CancelOrder: %w", err)
	}
	if err := s.server.RegisterHandler("orders.v1.OrderCommandService.UpdateOrderStatus", s.handleUpdateOrderStatus); err != nil {
		return fmt.Errorf("failed to register UpdateOrderStatus: %w", err)
	}

	return s.server.Start(ctx)
}

func (s *CqrsOrderCommandServiceServer) handleCreateOrder(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*CreateOrderRequest)
	result, err := s.handler.CreateOrder(ctx, req)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *CqrsOrderCommandServiceServer) handleCancelOrder(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*CancelOrderRequest)
	result, err := s.handler.CancelOrder(ctx, req)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *CqrsOrderCommandServiceServer) handleUpdateOrderStatus(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*UpdateOrderStatusRequest)
	result, err := s.handler.UpdateOrderStatus(ctx, req)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

// Close stops the server
func (s *CqrsOrderCommandServiceServer) Close() error {
	return s.server.Close()
}

// CqrsOrderQueryServiceHandler defines the business logic for OrderQueryService
type CqrsOrderQueryServiceHandler interface {
	GetOrder(ctx context.Context, query *GetOrderRequest) (*Order, error)
	ListOrders(ctx context.Context, query *ListOrdersRequest) (*ListOrdersResponse, error)
	GetOrdersByStatus(ctx context.Context, query *GetOrdersByStatusRequest) (*ListOrdersResponse, error)
}

// CqrsOrderQueryServiceServer routes requests to the CqrsOrderQueryServiceHandler implementation
type CqrsOrderQueryServiceServer struct {
	server  cqrs.Server
	handler CqrsOrderQueryServiceHandler
}

// NewCqrsOrderQueryServiceServer creates a new server
func NewCqrsOrderQueryServiceServer(server cqrs.Server, handler CqrsOrderQueryServiceHandler) *CqrsOrderQueryServiceServer {
	return &CqrsOrderQueryServiceServer{
		server:  server,
		handler: handler,
	}
}

// Start registers handlers and starts the server
func (s *CqrsOrderQueryServiceServer) Start(ctx context.Context) error {
	if err := s.server.RegisterHandler("orders.v1.OrderQueryService.GetOrder", s.handleGetOrder); err != nil {
		return fmt.Errorf("failed to register GetOrder: %w", err)
	}
	if err := s.server.RegisterHandler("orders.v1.OrderQueryService.ListOrders", s.handleListOrders); err != nil {
		return fmt.Errorf("failed to register ListOrders: %w", err)
	}
	if err := s.server.RegisterHandler("orders.v1.OrderQueryService.GetOrdersByStatus", s.handleGetOrdersByStatus); err != nil {
		return fmt.Errorf("failed to register GetOrdersByStatus: %w", err)
	}

	return s.server.Start(ctx)
}

func (s *CqrsOrderQueryServiceServer) handleGetOrder(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*GetOrderRequest)
	result, err := s.handler.GetOrder(ctx, req)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *CqrsOrderQueryServiceServer) handleListOrders(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*ListOrdersRequest)
	result, err := s.handler.ListOrders(ctx, req)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

func (s *CqrsOrderQueryServiceServer) handleGetOrdersByStatus(ctx context.Context, request proto.Message) (*eventsourcing.Response, error) {
	req := request.(*GetOrdersByStatusRequest)
	result, err := s.handler.GetOrdersByStatus(ctx, req)
	if err != nil {
		return &eventsourcing.Response{
			Success: false,
			Error:   eventsourcing.ErrorToAppError(err),
		}, nil
	}
	return eventsourcing.NewSuccessResponse(result)
}

// Close stops the server
func (s *CqrsOrderQueryServiceServer) Close() error {
	return s.server.Close()
}
