// Code generated by protoc-gen-cqrs. DO NOT EDIT.
// version: 0.0.1
// Server service for v1

package servicev1

import (
	"context"
	"fmt"

	"github.com/plaenen/eventstore/pkg/cqrs"
	"google.golang.org/protobuf/proto"
)

// CqrsAccountCommandServiceHandler defines the business logic for AccountCommandService
type CqrsAccountCommandServiceHandler interface {
	OpenAccount(ctx context.Context, cmd *OpenAccountCommand) (*OpenAccountResponse, error)
	Deposit(ctx context.Context, cmd *DepositCommand) (*DepositResponse, error)
	Withdraw(ctx context.Context, cmd *WithdrawCommand) (*WithdrawResponse, error)
	CloseAccount(ctx context.Context, cmd *CloseAccountCommand) (*CloseAccountResponse, error)
}

// CqrsAccountCommandServiceServer routes requests to the CqrsAccountCommandServiceHandler implementation
type CqrsAccountCommandServiceServer struct {
	server  cqrs.Server
	handler CqrsAccountCommandServiceHandler
}

// NewCqrsAccountCommandServiceServer creates a new server
func NewCqrsAccountCommandServiceServer(server cqrs.Server, handler CqrsAccountCommandServiceHandler) *CqrsAccountCommandServiceServer {
	return &CqrsAccountCommandServiceServer{
		server:  server,
		handler: handler,
	}
}

// Start registers handlers and starts the server
func (s *CqrsAccountCommandServiceServer) Start(ctx context.Context) error {
	if err := s.server.RegisterHandler("account.service.v1.AccountCommandService.OpenAccount", s.handleOpenAccount); err != nil {
		return fmt.Errorf("failed to register OpenAccount: %w", err)
	}
	if err := s.server.RegisterHandler("account.service.v1.AccountCommandService.Deposit", s.handleDeposit); err != nil {
		return fmt.Errorf("failed to register Deposit: %w", err)
	}
	if err := s.server.RegisterHandler("account.service.v1.AccountCommandService.Withdraw", s.handleWithdraw); err != nil {
		return fmt.Errorf("failed to register Withdraw: %w", err)
	}
	if err := s.server.RegisterHandler("account.service.v1.AccountCommandService.CloseAccount", s.handleCloseAccount); err != nil {
		return fmt.Errorf("failed to register CloseAccount: %w", err)
	}

	return s.server.Start(ctx)
}

// handleOpenAccount is the internal handler wrapper for OpenAccount
func (s *CqrsAccountCommandServiceServer) handleOpenAccount(ctx context.Context, request proto.Message) (proto.Message, error) {
	req := request.(*OpenAccountCommand)
	result, err := s.handler.OpenAccount(ctx, req)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// handleDeposit is the internal handler wrapper for Deposit
func (s *CqrsAccountCommandServiceServer) handleDeposit(ctx context.Context, request proto.Message) (proto.Message, error) {
	req := request.(*DepositCommand)
	result, err := s.handler.Deposit(ctx, req)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// handleWithdraw is the internal handler wrapper for Withdraw
func (s *CqrsAccountCommandServiceServer) handleWithdraw(ctx context.Context, request proto.Message) (proto.Message, error) {
	req := request.(*WithdrawCommand)
	result, err := s.handler.Withdraw(ctx, req)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// handleCloseAccount is the internal handler wrapper for CloseAccount
func (s *CqrsAccountCommandServiceServer) handleCloseAccount(ctx context.Context, request proto.Message) (proto.Message, error) {
	req := request.(*CloseAccountCommand)
	result, err := s.handler.CloseAccount(ctx, req)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Close stops the server
func (s *CqrsAccountCommandServiceServer) Close() error {
	return s.server.Close()
}

// CqrsAccountQueryServiceHandler defines the business logic for AccountQueryService
type CqrsAccountQueryServiceHandler interface {
	GetAccount(ctx context.Context, query *GetAccountRequest) (*AccountView, error)
	ListAccounts(ctx context.Context, query *ListAccountsRequest) (*ListAccountsResponse, error)
	GetAccountBalance(ctx context.Context, query *GetAccountBalanceRequest) (*BalanceView, error)
	GetAccountHistory(ctx context.Context, query *GetAccountHistoryRequest) (*AccountHistoryResponse, error)
}

// CqrsAccountQueryServiceServer routes requests to the CqrsAccountQueryServiceHandler implementation
type CqrsAccountQueryServiceServer struct {
	server  cqrs.Server
	handler CqrsAccountQueryServiceHandler
}

// NewCqrsAccountQueryServiceServer creates a new server
func NewCqrsAccountQueryServiceServer(server cqrs.Server, handler CqrsAccountQueryServiceHandler) *CqrsAccountQueryServiceServer {
	return &CqrsAccountQueryServiceServer{
		server:  server,
		handler: handler,
	}
}

// Start registers handlers and starts the server
func (s *CqrsAccountQueryServiceServer) Start(ctx context.Context) error {
	if err := s.server.RegisterHandler("account.service.v1.AccountQueryService.GetAccount", s.handleGetAccount); err != nil {
		return fmt.Errorf("failed to register GetAccount: %w", err)
	}
	if err := s.server.RegisterHandler("account.service.v1.AccountQueryService.ListAccounts", s.handleListAccounts); err != nil {
		return fmt.Errorf("failed to register ListAccounts: %w", err)
	}
	if err := s.server.RegisterHandler("account.service.v1.AccountQueryService.GetAccountBalance", s.handleGetAccountBalance); err != nil {
		return fmt.Errorf("failed to register GetAccountBalance: %w", err)
	}
	if err := s.server.RegisterHandler("account.service.v1.AccountQueryService.GetAccountHistory", s.handleGetAccountHistory); err != nil {
		return fmt.Errorf("failed to register GetAccountHistory: %w", err)
	}

	return s.server.Start(ctx)
}

// handleGetAccount is the internal handler wrapper for GetAccount
func (s *CqrsAccountQueryServiceServer) handleGetAccount(ctx context.Context, request proto.Message) (proto.Message, error) {
	req := request.(*GetAccountRequest)
	result, err := s.handler.GetAccount(ctx, req)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// handleListAccounts is the internal handler wrapper for ListAccounts
func (s *CqrsAccountQueryServiceServer) handleListAccounts(ctx context.Context, request proto.Message) (proto.Message, error) {
	req := request.(*ListAccountsRequest)
	result, err := s.handler.ListAccounts(ctx, req)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// handleGetAccountBalance is the internal handler wrapper for GetAccountBalance
func (s *CqrsAccountQueryServiceServer) handleGetAccountBalance(ctx context.Context, request proto.Message) (proto.Message, error) {
	req := request.(*GetAccountBalanceRequest)
	result, err := s.handler.GetAccountBalance(ctx, req)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// handleGetAccountHistory is the internal handler wrapper for GetAccountHistory
func (s *CqrsAccountQueryServiceServer) handleGetAccountHistory(ctx context.Context, request proto.Message) (proto.Message, error) {
	req := request.(*GetAccountHistoryRequest)
	result, err := s.handler.GetAccountHistory(ctx, req)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Close stops the server
func (s *CqrsAccountQueryServiceServer) Close() error {
	return s.server.Close()
}
