// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: identity/v1/identity.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tenant ID the user belongs to.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The user ID (subject) to authenticate as.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The application token (e.g., OIDC ID Token, or custom app token).
	// In a real implementation, this would be validated against an IDP.
	Token         string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeTokenRequest) Reset() {
	*x = ExchangeTokenRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeTokenRequest) ProtoMessage() {}

func (x *ExchangeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeTokenRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeTokenRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExchangeTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExchangeTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ExchangeTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The NATS User JWT.
	Jwt string `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	// The NATS User Seed (Private Key).
	// Combined with JWT, this forms the Creds file.
	Seed string `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	// The full NATS Creds file content (convenience).
	Creds string `protobuf:"bytes,3,opt,name=creds,proto3" json:"creds,omitempty"`
	// Expiration time of the credentials (unix timestamp).
	ExpiresAt     int64 `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeTokenResponse) Reset() {
	*x = ExchangeTokenResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeTokenResponse) ProtoMessage() {}

func (x *ExchangeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangeTokenResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeTokenResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *ExchangeTokenResponse) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *ExchangeTokenResponse) GetCreds() string {
	if x != nil {
		return x.Creds
	}
	return ""
}

func (x *ExchangeTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_identity_v1_identity_proto protoreflect.FileDescriptor

const file_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1aidentity/v1/identity.proto\x12\videntity.v1\"b\n" +
	"\x14ExchangeTokenRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"r\n" +
	"\x15ExchangeTokenResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\tR\x04seed\x12\x14\n" +
	"\x05creds\x18\x03 \x01(\tR\x05creds\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt2i\n" +
	"\x0fIdentityService\x12V\n" +
	"\rExchangeToken\x12!.identity.v1.ExchangeTokenRequest\x1a\".identity.v1.ExchangeTokenResponseB:Z8github.com/plaenen/eventstore/pkg/identity/v1;identityv1b\x06proto3"

var (
	file_identity_v1_identity_proto_rawDescOnce sync.Once
	file_identity_v1_identity_proto_rawDescData []byte
)

func file_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)))
	})
	return file_identity_v1_identity_proto_rawDescData
}

var file_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identity_v1_identity_proto_goTypes = []any{
	(*ExchangeTokenRequest)(nil),  // 0: identity.v1.ExchangeTokenRequest
	(*ExchangeTokenResponse)(nil), // 1: identity.v1.ExchangeTokenResponse
}
var file_identity_v1_identity_proto_depIdxs = []int32{
	0, // 0: identity.v1.IdentityService.ExchangeToken:input_type -> identity.v1.ExchangeTokenRequest
	1, // 1: identity.v1.IdentityService.ExchangeToken:output_type -> identity.v1.ExchangeTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identity_v1_identity_proto_init() }
func file_identity_v1_identity_proto_init() {
	if File_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_identity_v1_identity_proto_depIdxs,
		MessageInfos:      file_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_identity_v1_identity_proto = out.File
	file_identity_v1_identity_proto_goTypes = nil
	file_identity_v1_identity_proto_depIdxs = nil
}
