// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/v1/identity.proto

package identityv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/plaenen/eventstore/pkg/identity/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdentityServiceName is the fully-qualified name of the IdentityService service.
	IdentityServiceName = "identity.v1.IdentityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdentityServiceExchangeTokenProcedure is the fully-qualified name of the IdentityService's
	// ExchangeToken RPC.
	IdentityServiceExchangeTokenProcedure = "/identity.v1.IdentityService/ExchangeToken"
)

// IdentityServiceClient is a client for the identity.v1.IdentityService service.
type IdentityServiceClient interface {
	// ExchangeToken exchanges a third-party or app token for NATS User Credentials.
	ExchangeToken(context.Context, *connect.Request[v1.ExchangeTokenRequest]) (*connect.Response[v1.ExchangeTokenResponse], error)
}

// NewIdentityServiceClient constructs a client for the identity.v1.IdentityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdentityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdentityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	identityServiceMethods := v1.File_identity_v1_identity_proto.Services().ByName("IdentityService").Methods()
	return &identityServiceClient{
		exchangeToken: connect.NewClient[v1.ExchangeTokenRequest, v1.ExchangeTokenResponse](
			httpClient,
			baseURL+IdentityServiceExchangeTokenProcedure,
			connect.WithSchema(identityServiceMethods.ByName("ExchangeToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// identityServiceClient implements IdentityServiceClient.
type identityServiceClient struct {
	exchangeToken *connect.Client[v1.ExchangeTokenRequest, v1.ExchangeTokenResponse]
}

// ExchangeToken calls identity.v1.IdentityService.ExchangeToken.
func (c *identityServiceClient) ExchangeToken(ctx context.Context, req *connect.Request[v1.ExchangeTokenRequest]) (*connect.Response[v1.ExchangeTokenResponse], error) {
	return c.exchangeToken.CallUnary(ctx, req)
}

// IdentityServiceHandler is an implementation of the identity.v1.IdentityService service.
type IdentityServiceHandler interface {
	// ExchangeToken exchanges a third-party or app token for NATS User Credentials.
	ExchangeToken(context.Context, *connect.Request[v1.ExchangeTokenRequest]) (*connect.Response[v1.ExchangeTokenResponse], error)
}

// NewIdentityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdentityServiceHandler(svc IdentityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	identityServiceMethods := v1.File_identity_v1_identity_proto.Services().ByName("IdentityService").Methods()
	identityServiceExchangeTokenHandler := connect.NewUnaryHandler(
		IdentityServiceExchangeTokenProcedure,
		svc.ExchangeToken,
		connect.WithSchema(identityServiceMethods.ByName("ExchangeToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/identity.v1.IdentityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdentityServiceExchangeTokenProcedure:
			identityServiceExchangeTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdentityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdentityServiceHandler struct{}

func (UnimplementedIdentityServiceHandler) ExchangeToken(context.Context, *connect.Request[v1.ExchangeTokenRequest]) (*connect.Response[v1.ExchangeTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.IdentityService.ExchangeToken is not implemented"))
}
