// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: eventsourcing/options.proto

package eventsourcing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceOptions declares which aggregate a command service operates on
// This is the PRIMARY source of truth for aggregate association
type ServiceOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// REQUIRED: The name of the aggregate this service operates on
	// Example: "Account", "Order", "User"
	AggregateName string `protobuf:"bytes,1,opt,name=aggregate_name,json=aggregateName,proto3" json:"aggregate_name,omitempty"`
	// REQUIRED: The proto message name that represents the aggregate root
	// Example: "Account" (refers to message Account)
	// This allows the generator to find the aggregate root message even across multiple files
	AggregateRootMessage string `protobuf:"bytes,2,opt,name=aggregate_root_message,json=aggregateRootMessage,proto3" json:"aggregate_root_message,omitempty"`
	// OPTIONAL: Generate handler interface for aggregate methods with functional options
	// When true, generates {AggregateName}Handler interface with MethodOption support
	// Example: AccountHandler interface with methods receiving ...eventsourcing.MethodOption
	// This enables passing authentication, tracing, and other cross-cutting concerns
	// Default: false
	AggregateHandler bool `protobuf:"varint,3,opt,name=aggregate_handler,json=aggregateHandler,proto3" json:"aggregate_handler,omitempty"`
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsourcing_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_eventsourcing_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_eventsourcing_options_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceOptions) GetAggregateName() string {
	if x != nil {
		return x.AggregateName
	}
	return ""
}

func (x *ServiceOptions) GetAggregateRootMessage() string {
	if x != nil {
		return x.AggregateRootMessage
	}
	return ""
}

func (x *ServiceOptions) GetAggregateHandler() bool {
	if x != nil {
		return x.AggregateHandler
	}
	return false
}

// AggregateRootOptions marks a proto message as an aggregate root
// This is the ONLY option needed on the aggregate state message
type AggregateRootOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// REQUIRED: The field name that contains the aggregate ID
	// Example: "account_id", "order_id", "user_id"
	IdField string `protobuf:"bytes,1,opt,name=id_field,json=idField,proto3" json:"id_field,omitempty"`
	// OPTIONAL: Override the aggregate type name (defaults to message name)
	// Usually not needed unless message name differs from aggregate name
	TypeName string `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
}

func (x *AggregateRootOptions) Reset() {
	*x = AggregateRootOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsourcing_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateRootOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRootOptions) ProtoMessage() {}

func (x *AggregateRootOptions) ProtoReflect() protoreflect.Message {
	mi := &file_eventsourcing_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRootOptions.ProtoReflect.Descriptor instead.
func (*AggregateRootOptions) Descriptor() ([]byte, []int) {
	return file_eventsourcing_options_proto_rawDescGZIP(), []int{1}
}

func (x *AggregateRootOptions) GetIdField() string {
	if x != nil {
		return x.IdField
	}
	return ""
}

func (x *AggregateRootOptions) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

// EventOptions marks a message as an event and associates it with an aggregate
// This is REQUIRED for all events to enable:
// - Projection SDK generation
// - Event catalog/discovery
// - Cross-file event organization
//
// Field Mapping & State Updates:
// - NO field_mapping option - developer handles in ApplyEvent implementation
// - NO applies_to_state option - developer controls which fields update
// - More flexible, explicit, and testable
type EventOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// REQUIRED: The aggregate this event belongs to
	// Must match the aggregate_name from the service
	AggregateName string `protobuf:"bytes,1,opt,name=aggregate_name,json=aggregateName,proto3" json:"aggregate_name,omitempty"`
}

func (x *EventOptions) Reset() {
	*x = EventOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsourcing_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOptions) ProtoMessage() {}

func (x *EventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_eventsourcing_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOptions.ProtoReflect.Descriptor instead.
func (*EventOptions) Descriptor() ([]byte, []int) {
	return file_eventsourcing_options_proto_rawDescGZIP(), []int{2}
}

func (x *EventOptions) GetAggregateName() string {
	if x != nil {
		return x.AggregateName
	}
	return ""
}

var file_eventsourcing_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         50002,
		Name:          "eventsourcing.service",
		Tag:           "bytes,50002,opt,name=service",
		Filename:      "eventsourcing/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*AggregateRootOptions)(nil),
		Field:         50003,
		Name:          "eventsourcing.aggregate_root",
		Tag:           "bytes,50003,opt,name=aggregate_root",
		Filename:      "eventsourcing/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*EventOptions)(nil),
		Field:         50004,
		Name:          "eventsourcing.event",
		Tag:           "bytes,50004,opt,name=event",
		Filename:      "eventsourcing/options.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional eventsourcing.ServiceOptions service = 50002;
	E_Service = &file_eventsourcing_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional eventsourcing.AggregateRootOptions aggregate_root = 50003;
	E_AggregateRoot = &file_eventsourcing_options_proto_extTypes[1]
	// optional eventsourcing.EventOptions event = 50004;
	E_Event = &file_eventsourcing_options_proto_extTypes[2]
)

var File_eventsourcing_options_proto protoreflect.FileDescriptor

var file_eventsourcing_options_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x69, 0x6e, 0x67, 0x2f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x69, 0x6e, 0x67, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a,
	0x01, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x61, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b,
	0x0a, 0x11, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x14, 0x41,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x0c, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x61,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x3a, 0x5a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd2,
	0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3a, 0x6d,
	0x0a, 0x0e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74,
	0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xd3, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d,
	0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x3a, 0x54, 0x0a,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd4, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x69, 0x6e, 0x67, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x6c, 0x61, 0x65, 0x6e, 0x65, 0x6e, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eventsourcing_options_proto_rawDescOnce sync.Once
	file_eventsourcing_options_proto_rawDescData = file_eventsourcing_options_proto_rawDesc
)

func file_eventsourcing_options_proto_rawDescGZIP() []byte {
	file_eventsourcing_options_proto_rawDescOnce.Do(func() {
		file_eventsourcing_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_eventsourcing_options_proto_rawDescData)
	})
	return file_eventsourcing_options_proto_rawDescData
}

var file_eventsourcing_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eventsourcing_options_proto_goTypes = []interface{}{
	(*ServiceOptions)(nil),              // 0: eventsourcing.ServiceOptions
	(*AggregateRootOptions)(nil),        // 1: eventsourcing.AggregateRootOptions
	(*EventOptions)(nil),                // 2: eventsourcing.EventOptions
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
	(*descriptorpb.MessageOptions)(nil), // 4: google.protobuf.MessageOptions
}
var file_eventsourcing_options_proto_depIdxs = []int32{
	3, // 0: eventsourcing.service:extendee -> google.protobuf.ServiceOptions
	4, // 1: eventsourcing.aggregate_root:extendee -> google.protobuf.MessageOptions
	4, // 2: eventsourcing.event:extendee -> google.protobuf.MessageOptions
	0, // 3: eventsourcing.service:type_name -> eventsourcing.ServiceOptions
	1, // 4: eventsourcing.aggregate_root:type_name -> eventsourcing.AggregateRootOptions
	2, // 5: eventsourcing.event:type_name -> eventsourcing.EventOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_eventsourcing_options_proto_init() }
func file_eventsourcing_options_proto_init() {
	if File_eventsourcing_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eventsourcing_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsourcing_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateRootOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsourcing_options_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eventsourcing_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_eventsourcing_options_proto_goTypes,
		DependencyIndexes: file_eventsourcing_options_proto_depIdxs,
		MessageInfos:      file_eventsourcing_options_proto_msgTypes,
		ExtensionInfos:    file_eventsourcing_options_proto_extTypes,
	}.Build()
	File_eventsourcing_options_proto = out.File
	file_eventsourcing_options_proto_rawDesc = nil
	file_eventsourcing_options_proto_goTypes = nil
	file_eventsourcing_options_proto_depIdxs = nil
}
