// Code generated by protoc-gen-eventsourcing. DO NOT EDIT.
// version: 0.0.38

package projectionsv1

import (
	v1 "github.com/plaenen/eventstore/examples/pb/account/domain/v1"
	v11 "github.com/plaenen/eventstore/examples/pb/subscription/v1"
)

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/plaenen/eventstore/pkg/eventsourcing"
	"github.com/plaenen/eventstore/pkg/eventsourcing/store/sqlite"
	"google.golang.org/protobuf/proto"
)

// MyCustomProjectionSQLiteBuilder builds a SQLite-backed projection
type MyCustomProjectionSQLiteBuilder struct {
	builder *sqlite.SQLiteProjectionBuilder
}

// NewMyCustomProjectionSQLiteBuilder creates a new SQLite projection builder
func NewMyCustomProjectionSQLiteBuilder(name string, db *sql.DB, checkpointStore *sqlite.CheckpointStore, eventStore eventsourcing.EventStore) *MyCustomProjectionSQLiteBuilder {
	return &MyCustomProjectionSQLiteBuilder{
		builder: sqlite.NewSQLiteProjectionBuilder(name, db, checkpointStore, eventStore),
	}
}

// WithMigrations registers a migrations directory
func (b *MyCustomProjectionSQLiteBuilder) WithMigrations(migrationsFS interface{}, path string) *MyCustomProjectionSQLiteBuilder {
	// We use interface{} for fs to avoid importing io/fs if not needed, but sqlite builder expects fs.FS
	// Let's assume user passes fs.FS
	if fs, ok := migrationsFS.(interface {
		Open(string) (interface{}, error)
	}); ok {
		b.builder.WithMigrations(fs, path)
	}
	return b
}

// OnAccountOpened registers a handler for AccountOpenedEvent
func (b *MyCustomProjectionSQLiteBuilder) OnAccountOpened(handler func(context.Context, *sql.Tx, *v1.AccountOpenedEvent, *eventsourcing.EventEnvelope) error) *MyCustomProjectionSQLiteBuilder {
	eventType := "account.domain.v1.AccountOpenedEvent"
	b.builder.OnWithTx(eventType, func(ctx context.Context, tx *sql.Tx, envelope *eventsourcing.EventEnvelope) error {
		event := &v1.AccountOpenedEvent{}
		if err := proto.Unmarshal(envelope.Data, event); err != nil {
			return fmt.Errorf("failed to unmarshal AccountOpenedEvent: %w", err)
		}
		return handler(ctx, tx, event, envelope)
	})
	return b
}

// OnSubscriptionCreated registers a handler for SubscriptionCreatedEvent
func (b *MyCustomProjectionSQLiteBuilder) OnSubscriptionCreated(handler func(context.Context, *sql.Tx, *v11.SubscriptionCreatedEvent, *eventsourcing.EventEnvelope) error) *MyCustomProjectionSQLiteBuilder {
	eventType := "subscription.v1.SubscriptionCreatedEvent"
	b.builder.OnWithTx(eventType, func(ctx context.Context, tx *sql.Tx, envelope *eventsourcing.EventEnvelope) error {
		event := &v11.SubscriptionCreatedEvent{}
		if err := proto.Unmarshal(envelope.Data, event); err != nil {
			return fmt.Errorf("failed to unmarshal SubscriptionCreatedEvent: %w", err)
		}
		return handler(ctx, tx, event, envelope)
	})
	return b
}

// OnReset registers a function to reset the projection state
func (b *MyCustomProjectionSQLiteBuilder) OnReset(resetFunc func(context.Context, *sql.Tx) error) *MyCustomProjectionSQLiteBuilder {
	b.builder.OnReset(resetFunc)
	return b
}

// Build creates the projection
func (b *MyCustomProjectionSQLiteBuilder) Build() (eventsourcing.Projection, error) {
	return b.builder.Build()
}
