// Code generated by protoc-gen-eventsourcing. DO NOT EDIT.
// version: 0.0.38

package projectionsv1

import (
	v1 "github.com/plaenen/eventstore/examples/pb/account/domain/v1"
	v11 "github.com/plaenen/eventstore/examples/pb/subscription/v1"
)

import (
	"context"
	"fmt"

	"github.com/plaenen/eventstore/pkg/eventsourcing"
	"google.golang.org/protobuf/proto"
)

// MyCustomProjectionBuilder builds a projection that listens to specific events
type MyCustomProjectionBuilder struct {
	name      string
	handlers  map[string]func(context.Context, *eventsourcing.EventEnvelope) error
	resetFunc func(context.Context) error
}

// NewMyCustomProjectionBuilder creates a new projection builder
func NewMyCustomProjectionBuilder(name string) *MyCustomProjectionBuilder {
	return &MyCustomProjectionBuilder{
		name:     name,
		handlers: make(map[string]func(context.Context, *eventsourcing.EventEnvelope) error),
	}
}

// OnAccountOpened registers a handler for AccountOpenedEvent
func (b *MyCustomProjectionBuilder) OnAccountOpened(handler func(context.Context, *v1.AccountOpenedEvent, *eventsourcing.EventEnvelope) error) *MyCustomProjectionBuilder {
	eventType := "account.domain.v1.AccountOpenedEvent"
	b.handlers[eventType] = func(ctx context.Context, envelope *eventsourcing.EventEnvelope) error {
		event := &v1.AccountOpenedEvent{}
		if err := proto.Unmarshal(envelope.Data, event); err != nil {
			return fmt.Errorf("failed to unmarshal AccountOpenedEvent: %w", err)
		}
		return handler(ctx, event, envelope)
	}
	return b
}

// OnSubscriptionCreated registers a handler for SubscriptionCreatedEvent
func (b *MyCustomProjectionBuilder) OnSubscriptionCreated(handler func(context.Context, *v11.SubscriptionCreatedEvent, *eventsourcing.EventEnvelope) error) *MyCustomProjectionBuilder {
	eventType := "subscription.v1.SubscriptionCreatedEvent"
	b.handlers[eventType] = func(ctx context.Context, envelope *eventsourcing.EventEnvelope) error {
		event := &v11.SubscriptionCreatedEvent{}
		if err := proto.Unmarshal(envelope.Data, event); err != nil {
			return fmt.Errorf("failed to unmarshal SubscriptionCreatedEvent: %w", err)
		}
		return handler(ctx, event, envelope)
	}
	return b
}

// OnReset registers a function to reset the projection state
func (b *MyCustomProjectionBuilder) OnReset(resetFunc func(context.Context) error) *MyCustomProjectionBuilder {
	b.resetFunc = resetFunc
	return b
}

// Build creates the projection
func (b *MyCustomProjectionBuilder) Build() eventsourcing.Projection {
	return &MyCustomProjectionProjection{
		name:      b.name,
		handlers:  b.handlers,
		resetFunc: b.resetFunc,
	}
}

// MyCustomProjectionProjection implements eventsourcing.Projection with type-safe handlers
type MyCustomProjectionProjection struct {
	name      string
	handlers  map[string]func(context.Context, *eventsourcing.EventEnvelope) error
	resetFunc func(context.Context) error
}

// Name returns the projection name
func (p *MyCustomProjectionProjection) Name() string {
	return p.name
}

// Handle dispatches events to registered typed handlers
func (p *MyCustomProjectionProjection) Handle(ctx context.Context, envelope *eventsourcing.EventEnvelope) error {
	handler, exists := p.handlers[envelope.EventType]
	if !exists {
		// No handler registered for this event type - skip it
		return nil
	}
	return handler(ctx, envelope)
}

// Reset resets the projection state
func (p *MyCustomProjectionProjection) Reset(ctx context.Context) error {
	if p.resetFunc == nil {
		return nil // No reset function registered
	}
	return p.resetFunc(ctx)
}
