// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: account/domain/v1/account.proto

package domainv1

import (
	_ "github.com/plaenen/eventstore/pkg/eventsourcing"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_OPEN        AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_CLOSED      AccountStatus = 2
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_OPEN",
		2: "ACCOUNT_STATUS_CLOSED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_OPEN":        1,
		"ACCOUNT_STATUS_CLOSED":      2,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_account_domain_v1_account_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_account_domain_v1_account_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_account_domain_v1_account_proto_rawDescGZIP(), []int{0}
}

type Account struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OwnerName string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Balance   string                 `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Status    AccountStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=account.domain.v1.AccountStatus" json:"status,omitempty"`
	// NEW FIELDS demonstrating proto field evolution for upcasting
	Currency      string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`                     // Added later - defaults to "" for old snapshots
	CreatedAt     int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Added later - defaults to 0 for old snapshots
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_domain_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_domain_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_domain_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Account) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Account) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type AccountOpenedEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OwnerName string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	// FIELD EVOLUTION EXAMPLE: Field renamed over time
	//
	// Deprecated: Marked as deprecated in account/domain/v1/account.proto.
	InitialBalance string `protobuf:"bytes,3,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"` // V1: Old field name
	OpeningAmount  string `protobuf:"bytes,7,opt,name=opening_amount,json=openingAmount,proto3" json:"opening_amount,omitempty"`    // V2: New field name
	// NEW FIELDS: Added in V2
	Currency      string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`                     // Defaults to "" for V1 events
	CreatedAt     int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Defaults to 0 for V1 events
	Timestamp     int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountOpenedEvent) Reset() {
	*x = AccountOpenedEvent{}
	mi := &file_account_domain_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountOpenedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountOpenedEvent) ProtoMessage() {}

func (x *AccountOpenedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_account_domain_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountOpenedEvent.ProtoReflect.Descriptor instead.
func (*AccountOpenedEvent) Descriptor() ([]byte, []int) {
	return file_account_domain_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountOpenedEvent) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountOpenedEvent) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

// Deprecated: Marked as deprecated in account/domain/v1/account.proto.
func (x *AccountOpenedEvent) GetInitialBalance() string {
	if x != nil {
		return x.InitialBalance
	}
	return ""
}

func (x *AccountOpenedEvent) GetOpeningAmount() string {
	if x != nil {
		return x.OpeningAmount
	}
	return ""
}

func (x *AccountOpenedEvent) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountOpenedEvent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AccountOpenedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MoneyDepositedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	NewBalance    string                 `protobuf:"bytes,3,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyDepositedEvent) Reset() {
	*x = MoneyDepositedEvent{}
	mi := &file_account_domain_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyDepositedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyDepositedEvent) ProtoMessage() {}

func (x *MoneyDepositedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_account_domain_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyDepositedEvent.ProtoReflect.Descriptor instead.
func (*MoneyDepositedEvent) Descriptor() ([]byte, []int) {
	return file_account_domain_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *MoneyDepositedEvent) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *MoneyDepositedEvent) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MoneyDepositedEvent) GetNewBalance() string {
	if x != nil {
		return x.NewBalance
	}
	return ""
}

func (x *MoneyDepositedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MoneyWithdrawnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	NewBalance    string                 `protobuf:"bytes,3,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyWithdrawnEvent) Reset() {
	*x = MoneyWithdrawnEvent{}
	mi := &file_account_domain_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyWithdrawnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyWithdrawnEvent) ProtoMessage() {}

func (x *MoneyWithdrawnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_account_domain_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyWithdrawnEvent.ProtoReflect.Descriptor instead.
func (*MoneyWithdrawnEvent) Descriptor() ([]byte, []int) {
	return file_account_domain_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *MoneyWithdrawnEvent) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *MoneyWithdrawnEvent) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MoneyWithdrawnEvent) GetNewBalance() string {
	if x != nil {
		return x.NewBalance
	}
	return ""
}

func (x *MoneyWithdrawnEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AccountClosedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	FinalBalance  string                 `protobuf:"bytes,2,opt,name=final_balance,json=finalBalance,proto3" json:"final_balance,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountClosedEvent) Reset() {
	*x = AccountClosedEvent{}
	mi := &file_account_domain_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountClosedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountClosedEvent) ProtoMessage() {}

func (x *AccountClosedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_account_domain_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountClosedEvent.ProtoReflect.Descriptor instead.
func (*AccountClosedEvent) Descriptor() ([]byte, []int) {
	return file_account_domain_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *AccountClosedEvent) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountClosedEvent) GetFinalBalance() string {
	if x != nil {
		return x.FinalBalance
	}
	return ""
}

func (x *AccountClosedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AccountOpenedEventV1 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OwnerName      string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	InitialBalance string                 `protobuf:"bytes,3,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"` // Old field name
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccountOpenedEventV1) Reset() {
	*x = AccountOpenedEventV1{}
	mi := &file_account_domain_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountOpenedEventV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountOpenedEventV1) ProtoMessage() {}

func (x *AccountOpenedEventV1) ProtoReflect() protoreflect.Message {
	mi := &file_account_domain_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountOpenedEventV1.ProtoReflect.Descriptor instead.
func (*AccountOpenedEventV1) Descriptor() ([]byte, []int) {
	return file_account_domain_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *AccountOpenedEventV1) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountOpenedEventV1) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *AccountOpenedEventV1) GetInitialBalance() string {
	if x != nil {
		return x.InitialBalance
	}
	return ""
}

func (x *AccountOpenedEventV1) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_account_domain_v1_account_proto protoreflect.FileDescriptor

const file_account_domain_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1faccount/domain/v1/account.proto\x12\x11account.domain.v1\x1a\x1beventsourcing/options.proto\"\xe8\x01\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\x12\x18\n" +
	"\abalance\x18\x03 \x01(\tR\abalance\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .account.domain.v1.AccountStatusR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt:\x10\x9a\xb5\x18\f\n" +
	"\n" +
	"account_id\"\x8e\x02\n" +
	"\x12AccountOpenedEvent\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\x12+\n" +
	"\x0finitial_balance\x18\x03 \x01(\tB\x02\x18\x01R\x0einitialBalance\x12%\n" +
	"\x0eopening_amount\x18\a \x01(\tR\ropeningAmount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp:\r\xa2\xb5\x18\t\n" +
	"\aAccount\"\x9a\x01\n" +
	"\x13MoneyDepositedEvent\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1f\n" +
	"\vnew_balance\x18\x03 \x01(\tR\n" +
	"newBalance\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp:\r\xa2\xb5\x18\t\n" +
	"\aAccount\"\x9a\x01\n" +
	"\x13MoneyWithdrawnEvent\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1f\n" +
	"\vnew_balance\x18\x03 \x01(\tR\n" +
	"newBalance\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp:\r\xa2\xb5\x18\t\n" +
	"\aAccount\"\x85\x01\n" +
	"\x12AccountClosedEvent\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12#\n" +
	"\rfinal_balance\x18\x02 \x01(\tR\ffinalBalance\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp:\r\xa2\xb5\x18\t\n" +
	"\aAccount\"\xaa\x01\n" +
	"\x14AccountOpenedEventV1\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\x12'\n" +
	"\x0finitial_balance\x18\x03 \x01(\tR\x0einitialBalance\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp:\r\xa2\xb5\x18\t\n" +
	"\aAccount*c\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACCOUNT_STATUS_OPEN\x10\x01\x12\x19\n" +
	"\x15ACCOUNT_STATUS_CLOSED\x10\x02B\xd1\x01\n" +
	"\x15com.account.domain.v1B\fAccountProtoP\x01ZDgithub.com/plaenen/eventstore/examples/pb/account/domain/v1;domainv1\xa2\x02\x03ADX\xaa\x02\x11Account.Domain.V1\xca\x02\x11Account\\Domain\\V1\xe2\x02\x1dAccount\\Domain\\V1\\GPBMetadata\xea\x02\x13Account::Domain::V1b\x06proto3"

var (
	file_account_domain_v1_account_proto_rawDescOnce sync.Once
	file_account_domain_v1_account_proto_rawDescData []byte
)

func file_account_domain_v1_account_proto_rawDescGZIP() []byte {
	file_account_domain_v1_account_proto_rawDescOnce.Do(func() {
		file_account_domain_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_domain_v1_account_proto_rawDesc), len(file_account_domain_v1_account_proto_rawDesc)))
	})
	return file_account_domain_v1_account_proto_rawDescData
}

var file_account_domain_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_account_domain_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_account_domain_v1_account_proto_goTypes = []any{
	(AccountStatus)(0),           // 0: account.domain.v1.AccountStatus
	(*Account)(nil),              // 1: account.domain.v1.Account
	(*AccountOpenedEvent)(nil),   // 2: account.domain.v1.AccountOpenedEvent
	(*MoneyDepositedEvent)(nil),  // 3: account.domain.v1.MoneyDepositedEvent
	(*MoneyWithdrawnEvent)(nil),  // 4: account.domain.v1.MoneyWithdrawnEvent
	(*AccountClosedEvent)(nil),   // 5: account.domain.v1.AccountClosedEvent
	(*AccountOpenedEventV1)(nil), // 6: account.domain.v1.AccountOpenedEventV1
}
var file_account_domain_v1_account_proto_depIdxs = []int32{
	0, // 0: account.domain.v1.Account.status:type_name -> account.domain.v1.AccountStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_domain_v1_account_proto_init() }
func file_account_domain_v1_account_proto_init() {
	if File_account_domain_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_domain_v1_account_proto_rawDesc), len(file_account_domain_v1_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_domain_v1_account_proto_goTypes,
		DependencyIndexes: file_account_domain_v1_account_proto_depIdxs,
		EnumInfos:         file_account_domain_v1_account_proto_enumTypes,
		MessageInfos:      file_account_domain_v1_account_proto_msgTypes,
	}.Build()
	File_account_domain_v1_account_proto = out.File
	file_account_domain_v1_account_proto_goTypes = nil
	file_account_domain_v1_account_proto_depIdxs = nil
}
